import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:anicel/src/models/app_language.dart';
import 'package:anicel/src/ui/shortcuts/editor_action_registry.dart';
import 'package:anicel/src/ui/text/app_strings.dart';

/// The key contract behind the fallback table.
///
/// [AppStrings] resolves each getter through a string key into a per-language
/// map, falling back to English. That buys partial translations at the cost
/// of the compiler no longer checking the key — so this reads EVERY getter in
/// EVERY language. A typo'd key throws here instead of at the one moment a
/// user opens that panel in that language.
void main() {
  final readers = <String, String Function(AppStrings)>{
    'languageSettingsTitle': (s) => s.languageSettingsTitle,
    'programLanguageLabel': (s) => s.programLanguageLabel,
    'notationLanguageLabel': (s) => s.notationLanguageLabel,
    'programLanguageHelp': (s) => s.programLanguageHelp,
    'notationLanguageHelp': (s) => s.notationLanguageHelp,
    'noCutSelected': (s) => s.noCutSelected,
    'pageLabel': (s) => s.pageLabel,
    'continuousLabel': (s) => s.continuousLabel,
    'noticeNoFrameHere': (s) => s.noticeNoFrameHere,
    'noticeLayerNotDrawable': (s) => s.noticeLayerNotDrawable,
    'noticeEditAttachOwner': (s) => s.noticeEditAttachOwner,
    'commonCancel': (s) => s.commonCancel,
    'commonApply': (s) => s.commonApply,
    'commonRefresh': (s) => s.commonRefresh,
    'commonClose': (s) => s.commonClose,
    'exportNoCuts': (s) => s.exportNoCuts,
    'audioOffsetTitle': (s) => s.audioOffsetTitle,
    'audioOffsetHelp': (s) => s.audioOffsetHelp,
    'audioOffsetLabel': (s) => s.audioOffsetLabel,
    'audioUnitFrames': (s) => s.audioUnitFrames,
    'audioDevicesTitle': (s) => s.audioDevicesTitle,
    'audioDevicesHelp': (s) => s.audioDevicesHelp,
    'audioOutputLabel': (s) => s.audioOutputLabel,
    'audioInputLabel': (s) => s.audioInputLabel,
    'audioSystemDefault': (s) => s.audioSystemDefault,
    'audioDeviceDefaultSuffix': (s) => s.audioDeviceDefaultSuffix,
    'audioDeviceMissingSuffix': (s) => s.audioDeviceMissingSuffix,
    'audioSyncInspectorTitle': (s) => s.audioSyncInspectorTitle,
    'recordVoiceTooltip': (s) => s.recordVoiceTooltip,
    'recordVoiceStopTooltip': (s) => s.recordVoiceStopTooltip,
    'recordMicOpenFailed': (s) => s.recordMicOpenFailed,
    'recordMicPermissionDenied': (s) => s.recordMicPermissionDenied,
    'recordSelectSeLane': (s) => s.recordSelectSeLane,
    'recordTakeClipped': (s) => s.recordTakeClipped,
    'recordClipMarkerTooltip': (s) => s.recordClipMarkerTooltip,
    'audioMicGainLabel': (s) => s.audioMicGainLabel,
    'audioInputChannelLabel': (s) => s.audioInputChannelLabel,
    'audioInputChannelDevice': (s) => s.audioInputChannelDevice,
    'audioInputChannelMonoMix': (s) => s.audioInputChannelMonoMix,
    'audioInputChannelLeft': (s) => s.audioInputChannelLeft,
    'audioInputChannelRight': (s) => s.audioInputChannelRight,
    'audioClippingNoticeLabel': (s) => s.audioClippingNoticeLabel,
    'audioDenoiseLabel': (s) => s.audioDenoiseLabel,
    'audioInputMeterLabel': (s) => s.audioInputMeterLabel,
    'audioTestSoundLabel': (s) => s.audioTestSoundLabel,
    'audioCountInLabel': (s) => s.audioCountInLabel,
    'audioCueBeepsLabel': (s) => s.audioCueBeepsLabel,
    'audioStreamerLabel': (s) => s.audioStreamerLabel,
    'recordNothingRecording': (s) => s.recordNothingRecording,
    'recordTakeEmpty': (s) => s.recordTakeEmpty,
    'recordPlacementFailed': (s) => s.recordPlacementFailed,
    'recordDroppedFramesTemplate': (s) => s.recordDroppedFramesTemplate,
    'layerAudioTitle': (s) => s.layerAudioTitle,
    'audioGainLabel': (s) => s.audioGainLabel,
    'audioPanLabel': (s) => s.audioPanLabel,
    'layerAudioPanHelp': (s) => s.layerAudioPanHelp,
    'audioMute': (s) => s.audioMute,
    'audioSolo': (s) => s.audioSolo,
    'fpsAudioTitleTemplate': (s) => s.fpsAudioTitleTemplate,
    'fpsAudioBody': (s) => s.fpsAudioBody,
    'fpsAudioKeep': (s) => s.fpsAudioKeep,
    'fpsAudioPull': (s) => s.fpsAudioPull,
    'selectionMoveConfirmTitle': (s) => s.selectionMoveConfirmTitle,
    'selectionMoveConfirmBody': (s) => s.selectionMoveConfirmBody,
    'selectionMoveRevert': (s) => s.selectionMoveRevert,
    'selectionMoveApply': (s) => s.selectionMoveApply,
    'selectionClosePolygon': (s) => s.selectionClosePolygon,
    'commonSave': (s) => s.commonSave,
    'commonDelete': (s) => s.commonDelete,
    'commonRename': (s) => s.commonRename,
    'commonLink': (s) => s.commonLink,
    'commonPreview': (s) => s.commonPreview,
    'renameLayerTitle': (s) => s.renameLayerTitle,
    'renameLayerField': (s) => s.renameLayerField,
    'renameLayerEmpty': (s) => s.renameLayerEmpty,
    'renameCutTitle': (s) => s.renameCutTitle,
    'renameCutField': (s) => s.renameCutField,
    'renameCutEmpty': (s) => s.renameCutEmpty,
    'renameFrameTitle': (s) => s.renameFrameTitle,
    'renameFrameField': (s) => s.renameFrameField,
    'renameKeyTitle': (s) => s.renameKeyTitle,
    'renameKeyField': (s) => s.renameKeyField,
    'cutNoteTitle': (s) => s.cutNoteTitle,
    'cutNoteField': (s) => s.cutNoteField,
    'deleteLayerTitle': (s) => s.deleteLayerTitle,
    'deleteLayerMessageTemplate': (s) => s.deleteLayerMessageTemplate,
    'frameNameConflictTitle': (s) => s.frameNameConflictTitle,
    'frameNameConflictBody': (s) => s.frameNameConflictBody,
    'seInstanceNewTitle': (s) => s.seInstanceNewTitle,
    'seInstanceEditTitle': (s) => s.seInstanceEditTitle,
    'seNameLabel': (s) => s.seNameLabel,
    'seDialogueLabel': (s) => s.seDialogueLabel,
    'tlResetGroup': (s) => s.tlResetGroup,
    'seNameTagShowLineLabel': (s) => s.seNameTagShowLineLabel,
    'seNameTagLineInkLabel': (s) => s.seNameTagLineInkLabel,
    'seNameTagPreviewName': (s) => s.seNameTagPreviewName,
    'seNameTagPreviewLine': (s) => s.seNameTagPreviewLine,
    'seLinkedAudioLabel': (s) => s.seLinkedAudioLabel,
    'seLinkedAudioNone': (s) => s.seLinkedAudioNone,
    'seUnlinkAudio': (s) => s.seUnlinkAudio,
    'cameraKeyTitleTemplate': (s) => s.cameraKeyTitleTemplate,
    'cameraKeyLinear': (s) => s.cameraKeyLinear,
    'cameraKeyHold': (s) => s.cameraKeyHold,
    'convertLinkedCutTitle': (s) => s.convertLinkedCutTitle,
    'convertLinkedCutBodyTemplate': (s) => s.convertLinkedCutBodyTemplate,
    'convertLinkedCutTargetLabel': (s) => s.convertLinkedCutTargetLabel,
    'convertLinkedCutLinksTemplate': (s) => s.convertLinkedCutLinksTemplate,
    'convertLinkedCutReplacedTemplate': (s) =>
        s.convertLinkedCutReplacedTemplate,
    'convertLinkedCutJoiningTemplate': (s) => s.convertLinkedCutJoiningTemplate,
    'convertLinkedCutTargetGainsTemplate': (s) =>
        s.convertLinkedCutTargetGainsTemplate,
    'convertLinkedCutOriginGainsTemplate': (s) =>
        s.convertLinkedCutOriginGainsTemplate,
    'convertLinkedCutNothing': (s) => s.convertLinkedCutNothing,
    'convertLinkedCutUndoNote': (s) => s.convertLinkedCutUndoNote,
    'convertLinkedCutResizeFirst': (s) => s.convertLinkedCutResizeFirst,
    'toolGuide': (s) => s.toolGuide,
    'guideKindSymmetry': (s) => s.guideKindSymmetry,
    'guideKindPerspective': (s) => s.guideKindPerspective,
    'guideAdd': (s) => s.guideAdd,
    'guideDelete': (s) => s.guideDelete,
    'guideShow': (s) => s.guideShow,
    'guideActsOn': (s) => s.guideActsOn,
    'guideActsOff': (s) => s.guideActsOff,
    'guideLibraryEmpty': (s) => s.guideLibraryEmpty,
    'guideSelectPrompt': (s) => s.guideSelectPrompt,
    'guideLineCount': (s) => s.guideLineCount,
    'guideMirrorMode': (s) => s.guideMirrorMode,
    'guideMirrorModeOn': (s) => s.guideMirrorModeOn,
    'guideMirrorModeOff': (s) => s.guideMirrorModeOff,
    'guideSnap': (s) => s.guideSnap,
    'guideSnapNote': (s) => s.guideSnapNote,
    'guideEyeLevelShow': (s) => s.guideEyeLevelShow,
    'guideConstrainToEyeLevel': (s) => s.guideConstrainToEyeLevel,
    'guideConstrainToEyeLevelNote': (s) => s.guideConstrainToEyeLevelNote,
    'guideVanishingPoint': (s) => s.guideVanishingPoint,
    'guideVanishingPointAtInfinity': (s) => s.guideVanishingPointAtInfinity,
    'guideAddVanishingPoint': (s) => s.guideAddVanishingPoint,
    'guideMakeVertical': (s) => s.guideMakeVertical,
    'recoverAutosaveTitle': (s) => s.recoverAutosaveTitle,
    'recoverAutosaveBody': (s) => s.recoverAutosaveBody,
    'recoverOpenSaved': (s) => s.recoverOpenSaved,
    'recoverAction': (s) => s.recoverAction,
    'closeProjectTitle': (s) => s.closeProjectTitle,
    'closeProjectBody': (s) => s.closeProjectBody,
    'commonSaveAs': (s) => s.commonSaveAs,
    'unsavedAutosaveTitle': (s) => s.unsavedAutosaveTitle,
    'unsavedAutosaveBody': (s) => s.unsavedAutosaveBody,
    'commonNotNow': (s) => s.commonNotNow,
    'menuBarFile': (s) => s.menuBarFile,
    'menuBarEdit': (s) => s.menuBarEdit,
    'menuBarCut': (s) => s.menuBarCut,
    'menuBarLayer': (s) => s.menuBarLayer,
    'menuBarPlayback': (s) => s.menuBarPlayback,
    'menuBarWindow': (s) => s.menuBarWindow,
    'menuBarHelp': (s) => s.menuBarHelp,
    'menuPlay': (s) => s.menuPlay,
    'menuPause': (s) => s.menuPause,
    'menuAlphaPreview': (s) => s.menuAlphaPreview,
    'topStripProject': (s) => s.topStripProject,
    'topStripSettings': (s) => s.topStripSettings,
    'fileOpenTitle': (s) => s.fileOpenTitle,
    'fileSaveTitle': (s) => s.fileSaveTitle,
    'fileStorageOffNotice': (s) => s.fileStorageOffNotice,
    'fileOpenSettings': (s) => s.fileOpenSettings,
    'fileNameLabel': (s) => s.fileNameLabel,
    'fileCloudNoticeOpen': (s) => s.fileCloudNoticeOpen,
    'replaceFileTitle': (s) => s.replaceFileTitle,
    'replaceFileMessageTemplate': (s) => s.replaceFileMessageTemplate,
    'commonReplace': (s) => s.commonReplace,
    'folderNoPathTitle': (s) => s.folderNoPathTitle,
    'folderStorageOffTitle': (s) => s.folderStorageOffTitle,
    'folderPickUnavailable': (s) => s.folderPickUnavailable,
    'projectChooserEmpty': (s) => s.projectChooserEmpty,
    'fileNameEmpty': (s) => s.fileNameEmpty,
    'recentProjectsTitle': (s) => s.recentProjectsTitle,
    'recentReconnect': (s) => s.recentReconnect,
    'sortByName': (s) => s.sortByName,
    'sortByModified': (s) => s.sortByModified,
    'sortBySize': (s) => s.sortBySize,
    'sortAscending': (s) => s.sortAscending,
    'sortDescending': (s) => s.sortDescending,
    'canvasSizeTitle': (s) => s.canvasSizeTitle,
    'canvasWidthLabel': (s) => s.canvasWidthLabel,
    'canvasHeightLabel': (s) => s.canvasHeightLabel,
    'canvasAnchorHelpTemplate': (s) => s.canvasAnchorHelpTemplate,
    'canvasPresetDefault': (s) => s.canvasPresetDefault,
    'commonResize': (s) => s.commonResize,
    'backgroundTitle': (s) => s.backgroundTitle,
    'backgroundPaper': (s) => s.backgroundPaper,
    'backgroundWhite': (s) => s.backgroundWhite,
    'backgroundBlack': (s) => s.backgroundBlack,
    'backgroundTransparent': (s) => s.backgroundTransparent,
    'backgroundCustom': (s) => s.backgroundCustom,
    'backgroundHelp': (s) => s.backgroundHelp,
    'inputTitle': (s) => s.inputTitle,
    'inputTouchScroll': (s) => s.inputTouchScroll,
    'inputTouchScrollHelp': (s) => s.inputTouchScrollHelp,
    'inputPressureHeading': (s) => s.inputPressureHeading,
    'inputPressureSoftHard': (s) => s.inputPressureSoftHard,
    'inputPressureLinear': (s) => s.inputPressureLinear,
    'inputCanvasHeading': (s) => s.inputCanvasHeading,
    'inputRightClick': (s) => s.inputRightClick,
    'inputWheelClick': (s) => s.inputWheelClick,
    'inputCanvasTouchHeading': (s) => s.inputCanvasTouchHeading,
    'inputDragOneFinger': (s) => s.inputDragOneFinger,
    'inputDragTwoFingers': (s) => s.inputDragTwoFingers,
    'inputDragThreeFingers': (s) => s.inputDragThreeFingers,
    'inputExtraFinger': (s) => s.inputExtraFinger,
    'inputExtraFingerHelp': (s) => s.inputExtraFingerHelp,
    'inputTwoFingerRotation': (s) => s.inputTwoFingerRotation,
    'inputTwoFingerRotationHelp': (s) => s.inputTwoFingerRotationHelp,
    'inputRotationLock': (s) => s.inputRotationLock,
    'inputRotationLockHelp': (s) => s.inputRotationLockHelp,
    'inputRotationSnap': (s) => s.inputRotationSnap,
    'inputZoomSnaps': (s) => s.inputZoomSnaps,
    'inputBrushSizeSnaps': (s) => s.inputBrushSizeSnaps,
    'inputTabletHeading': (s) => s.inputTabletHeading,
    'inputTabletStandard': (s) => s.inputTabletStandard,
    'inputTabletStandardHelp': (s) => s.inputTabletStandardHelp,
    'inputTabletWintab': (s) => s.inputTabletWintab,
    'inputTabletWintabHelp': (s) => s.inputTabletWintabHelp,
    'inputTabletAutoDemoted': (s) => s.inputTabletAutoDemoted,
    'inputPenTail': (s) => s.inputPenTail,
    'inputFlipHaptics': (s) => s.inputFlipHaptics,
    'inputFlipHapticsHelp': (s) => s.inputFlipHapticsHelp,
    'dragActionFlip': (s) => s.dragActionFlip,
    'dragActionScreen': (s) => s.dragActionScreen,
    'dragActionBrushSize': (s) => s.dragActionBrushSize,
    'dragActionDraw': (s) => s.dragActionDraw,
    'commonNone': (s) => s.commonNone,
    'mapEyedropper': (s) => s.mapEyedropper,
    'mapEraser': (s) => s.mapEraser,
    'mapPan': (s) => s.mapPan,
    'mapUndo': (s) => s.mapUndo,
    'mapRedo': (s) => s.mapRedo,
    'holdReturnToTool': (s) => s.holdReturnToTool,
    'holdKeep': (s) => s.holdKeep,
    'prefsTitle': (s) => s.prefsTitle,
    'prefsInput': (s) => s.prefsInput,
    'prefsAutosave': (s) => s.prefsAutosave,
    'prefsAudio': (s) => s.prefsAudio,
    'prefsLanguage': (s) => s.prefsLanguage,
    'prefsAccent': (s) => s.prefsAccent,
    'prefsSystem': (s) => s.prefsSystem,
    'accentTitle': (s) => s.accentTitle,
    'accent1Label': (s) => s.accent1Label,
    'accent1Help': (s) => s.accent1Help,
    'sheetInfoTitle': (s) => s.sheetInfoTitle,
    'sheetFieldTitle': (s) => s.sheetFieldTitle,
    'sheetFieldEpisode': (s) => s.sheetFieldEpisode,
    'sheetFieldScene': (s) => s.sheetFieldScene,
    'sheetFieldCut': (s) => s.sheetFieldCut,
    'sheetFieldTime': (s) => s.sheetFieldTime,
    'sheetFieldName': (s) => s.sheetFieldName,
    'sheetFieldSheet': (s) => s.sheetFieldSheet,
    'sheetTitleHint': (s) => s.sheetTitleHint,
    'sheetArtist': (s) => s.sheetArtist,
    'sheetVisibleBoxes': (s) => s.sheetVisibleBoxes,
    'sheetNotation': (s) => s.sheetNotation,
    'sheetExposureBar': (s) => s.sheetExposureBar,
    'sheetExposureBarHelp': (s) => s.sheetExposureBarHelp,
    'sheetExposureBarN': (s) => s.sheetExposureBarN,
    'sheetSeEmptyFill': (s) => s.sheetSeEmptyFill,
    'instructionsTitle': (s) => s.instructionsTitle,
    'instructionEditTooltip': (s) => s.instructionEditTooltip,
    'instructionDeleteTooltip': (s) => s.instructionDeleteTooltip,
    'instructionAddButton': (s) => s.instructionAddButton,
    'instructionDefTitle': (s) => s.instructionDefTitle,
    'instructionDefNameLabel': (s) => s.instructionDefNameLabel,
    'instructionEventEditTitle': (s) => s.instructionEventEditTitle,
    'instructionEventAddTitle': (s) => s.instructionEventAddTitle,
    'instructionMarkLabel': (s) => s.instructionMarkLabel,
    'instructionNameLabel': (s) => s.instructionNameLabel,
    'instructionStartLabel': (s) => s.instructionStartLabel,
    'instructionEndLabel': (s) => s.instructionEndLabel,
    'instructionMemoLabel': (s) => s.instructionMemoLabel,
    'instructionEditSetButton': (s) => s.instructionEditSetButton,
    'cutCommands': (s) => s.cutCommands,
    'sbTrackFxCommands': (s) => s.sbTrackFxCommands,
    'cutAddCut': (s) => s.cutAddCut,
    'cutNewCut': (s) => s.cutNewCut,
    'cutDuplicateCut': (s) => s.cutDuplicateCut,
    'cutDuplicateActive': (s) => s.cutDuplicateActive,
    'cutRename': (s) => s.cutRename,
    'cutEditNote': (s) => s.cutEditNote,
    'cutMoveLeft': (s) => s.cutMoveLeft,
    'cutMoveRight': (s) => s.cutMoveRight,
    'cutDelete': (s) => s.cutDelete,
    'mediaActions': (s) => s.mediaActions,
    'mediaImportAudio': (s) => s.mediaImportAudio,
    'mediaRename': (s) => s.mediaRename,
    'mediaRelink': (s) => s.mediaRelink,
    'mediaMissingCount': (s) => s.mediaMissingCount,
    'mediaFindInFolder': (s) => s.mediaFindInFolder,
    'mediaRelinkFound': (s) => s.mediaRelinkFound,
    'mediaRemove': (s) => s.mediaRemove,
    'mediaRegisterInProject': (s) => s.mediaRegisterInProject,
    'mediaAlreadyInProject': (s) => s.mediaAlreadyInProject,
    'projectLegacyAssetsFolder': (s) => s.projectLegacyAssetsFolder,
    'mediaStillLinked': (s) => s.mediaStillLinked,
    'mediaOpenInViewer': (s) => s.mediaOpenInViewer,
    'mediaOpenInSubViewer': (s) => s.mediaOpenInSubViewer,
    'mediaViewerEmpty': (s) => s.mediaViewerEmpty,
    'mediaViewerOpenFile': (s) => s.mediaViewerOpenFile,
    'mediaViewerLoadFailed': (s) => s.mediaViewerLoadFailed,
    'mediaViewerCannotDisplay': (s) => s.mediaViewerCannotDisplay,
    'mediaViewerNoPdfRenderer': (s) => s.mediaViewerNoPdfRenderer,
    'mediaViewerSwap': (s) => s.mediaViewerSwap,
    'mediaViewerRegisterAsset': (s) => s.mediaViewerRegisterAsset,
    'panelCanvas': (s) => s.panelCanvas,
    'panelColorWheel': (s) => s.panelColorWheel,
    'panelColorRgb': (s) => s.panelColorRgb,
    'panelColorPalette': (s) => s.panelColorPalette,
    'panelMedia': (s) => s.panelMedia,
    'panelMediaViewer': (s) => s.panelMediaViewer,
    'panelMediaViewerSub': (s) => s.panelMediaViewerSub,
    'panelOnionSkin': (s) => s.panelOnionSkin,
    'panelStoryboard': (s) => s.panelStoryboard,
    'panelTimeline': (s) => s.panelTimeline,
    'panelTimesheet': (s) => s.panelTimesheet,
    'panelToolLibrary': (s) => s.panelToolLibrary,
    'panelCollapseRegion': (s) => s.panelCollapseRegion,
    'panelNewGroup': (s) => s.panelNewGroup,
    'panelRegionWidth': (s) => s.panelRegionWidth,
    'panelExpandRegion': (s) => s.panelExpandRegion,
    'panelToolSettings': (s) => s.panelToolSettings,
    'panelTools': (s) => s.panelTools,
    'onionBefore': (s) => s.onionBefore,
    'onionAfter': (s) => s.onionAfter,
    'onionBeforeTint': (s) => s.onionBeforeTint,
    'onionAfterTint': (s) => s.onionAfterTint,
    'onionGhostColorHelp': (s) => s.onionGhostColorHelp,
    'onionPegCountHelp': (s) => s.onionPegCountHelp,
    'shortcutTitle': (s) => s.shortcutTitle,
    'shortcutResetAll': (s) => s.shortcutResetAll,
    'shortcutResetToDefault': (s) => s.shortcutResetToDefault,
    'shortcutRecordNew': (s) => s.shortcutRecordNew,
    'shortcutTouch': (s) => s.shortcutTouch,
    'shortcutSearch': (s) => s.shortcutSearch,
    'shortcutConflictBanner': (s) => s.shortcutConflictBanner,
    'shortcutRecordingHint': (s) => s.shortcutRecordingHint,
    'playbackQuality': (s) => s.playbackQuality,
    'playbackStop': (s) => s.playbackStop,
    'playbackToStart': (s) => s.playbackToStart,
    'sheetPreviousPage': (s) => s.sheetPreviousPage,
    'sheetNextPage': (s) => s.sheetNextPage,
    'sheetPageDrag': (s) => s.sheetPageDrag,
    'autosaveTitle': (s) => s.autosaveTitle,
    'autosaveChoose': (s) => s.autosaveChoose,
    'autosaveDefault': (s) => s.autosaveDefault,
    'autosaveSidecarFolder': (s) => s.autosaveSidecarFolder,
    'exExport': (s) => s.exExport,
    'exAddToQueue': (s) => s.exAddToQueue,
    'exImage': (s) => s.exImage,
    'exVideo': (s) => s.exVideo,
    'exCels': (s) => s.exCels,
    'exSheetPng': (s) => s.exSheetPng,
    'exFormat': (s) => s.exFormat,
    'exOptions': (s) => s.exOptions,
    'exNaming': (s) => s.exNaming,
    'exScope': (s) => s.exScope,
    'exQuality': (s) => s.exQuality,
    'exCodec': (s) => s.exCodec,
    'exBitrate': (s) => s.exBitrate,
    'exChannels': (s) => s.exChannels,
    'exAudio': (s) => s.exAudio,
    'exFilter': (s) => s.exFilter,
    'exBrowse': (s) => s.exBrowse,
    'exSavePreset': (s) => s.exSavePreset,
    'exPresetNameEmpty': (s) => s.exPresetNameEmpty,
    'exBaseName': (s) => s.exBaseName,
    'exSuffix': (s) => s.exSuffix,
    'exDigits': (s) => s.exDigits,
    'exApplyLayerFx': (s) => s.exApplyLayerFx,
    'exApplyLayerFxHelp': (s) => s.exApplyLayerFxHelp,
    'exOnTimesheetOnly': (s) => s.exOnTimesheetOnly,
    'exInstructionLayer': (s) => s.exInstructionLayer,
    'exMuxSeMix': (s) => s.exMuxSeMix,
    'exCutFolder': (s) => s.exCutFolder,
    'exLayerFolder': (s) => s.exLayerFolder,
    'exProjectName': (s) => s.exProjectName,
    'exProject': (s) => s.exProject,
    'exCut': (s) => s.exCut,
    'exFreeAttach': (s) => s.exFreeAttach,
    'exSyncAttach': (s) => s.exSyncAttach,
    'exFolderMembers': (s) => s.exFolderMembers,
    'exWhite': (s) => s.exWhite,
    'exBlack': (s) => s.exBlack,
    'exCameraTemplate': (s) => s.exCameraTemplate,
    'exLayersTemplate': (s) => s.exLayersTemplate,
    'toolBrush': (s) => s.toolBrush,
    'toolEraser': (s) => s.toolEraser,
    'toolEyedropper': (s) => s.toolEyedropper,
    'toolFill': (s) => s.toolFill,
    'toolSelect': (s) => s.toolSelect,
    'toolMove': (s) => s.toolMove,
    'toolBrushTip': (s) => s.toolBrushTip,
    'toolEraserTip': (s) => s.toolEraserTip,
    'toolEyedropperTip': (s) => s.toolEyedropperTip,
    'toolFillTip': (s) => s.toolFillTip,
    'toolSelectTip': (s) => s.toolSelectTip,
    'toolMoveTip': (s) => s.toolMoveTip,
    'toolCutTip': (s) => s.toolCutTip,
    'brRenameTip': (s) => s.brRenameTip,
    'brDeleteTip': (s) => s.brDeleteTip,
    'brSize': (s) => s.brSize,
    'brOpacity': (s) => s.brOpacity,
    'brFlow': (s) => s.brFlow,
    'brHardness': (s) => s.brHardness,
    'brSpacing': (s) => s.brSpacing,
    'brAngle': (s) => s.brAngle,
    'brRoundness': (s) => s.brRoundness,
    'brScale': (s) => s.brScale,
    'brStabilizer': (s) => s.brStabilizer,
    'brBlend': (s) => s.brBlend,
    'brBlendMode': (s) => s.brBlendMode,
    'brFeather': (s) => s.brFeather,
    'brTolerance': (s) => s.brTolerance,
    'brGapClose': (s) => s.brGapClose,
    'brGrowShrink': (s) => s.brGrowShrink,
    'brAntiAlias': (s) => s.brAntiAlias,
    'brAntiAliasEdge': (s) => s.brAntiAliasEdge,
    'brTransformPreserveColors': (s) => s.brTransformPreserveColors,
    'brTransformPreserveColorsHint': (s) => s.brTransformPreserveColorsHint,
    'brFillBeyondCanvas': (s) => s.brFillBeyondCanvas,
    'brOpenRegionsRefuse': (s) => s.brOpenRegionsRefuse,
    'brName': (s) => s.brName,
    'brDisplay': (s) => s.brDisplay,
    'brTipIcon': (s) => s.brTipIcon,
    'brStrokePreview': (s) => s.brStrokePreview,
    'brBrushOptions': (s) => s.brBrushOptions,
    'brGroupOptions': (s) => s.brGroupOptions,
    'brNewGroup': (s) => s.brNewGroup,
    'brRenameGroup': (s) => s.brRenameGroup,
    'brDeleteGroup': (s) => s.brDeleteGroup,
    'brRenameSelected': (s) => s.brRenameSelected,
    'brDeleteSelected': (s) => s.brDeleteSelected,
    'brSaveAsPreset': (s) => s.brSaveAsPreset,
    'brImportBrushes': (s) => s.brImportBrushes,
    'brResetLibrary': (s) => s.brResetLibrary,
    'brExpand': (s) => s.brExpand,
    'brMeshWarp': (s) => s.brMeshWarp,
    'brBrushTip': (s) => s.brBrushTip,
    'brTipNone': (s) => s.brTipNone,
    'brAddTipImage': (s) => s.brAddTipImage,
    'brTipRotation': (s) => s.brTipRotation,
    'brRotationFixed': (s) => s.brRotationFixed,
    'brRotationDirection': (s) => s.brRotationDirection,
    'brDualTip': (s) => s.brDualTip,
    'brTexture': (s) => s.brTexture,
    'brTextureDensity': (s) => s.brTextureDensity,
    'brScatter': (s) => s.brScatter,
    'brScatterCount': (s) => s.brScatterCount,
    'brScatterBothAxes': (s) => s.brScatterBothAxes,
    'brSizeJitter': (s) => s.brSizeJitter,
    'brAngleJitter': (s) => s.brAngleJitter,
    'brRoundnessJitter': (s) => s.brRoundnessJitter,
    'brOpacityJitter': (s) => s.brOpacityJitter,
    'brSpacingJitter': (s) => s.brSpacingJitter,
    'brMixing': (s) => s.brMixing,
    'brPaintAmount': (s) => s.brPaintAmount,
    'brPaintDensity': (s) => s.brPaintDensity,
    'brColorStretch': (s) => s.brColorStretch,
    'trModeNormal': (s) => s.trModeNormal,
    'trModePerspective': (s) => s.trModePerspective,
    'trFlipHorizontal': (s) => s.trFlipHorizontal,
    'trFlipVertical': (s) => s.trFlipVertical,
    'trAnchor': (s) => s.trAnchor,
    'trAnchorOpposite': (s) => s.trAnchorOpposite,
    'trAnchorCenter': (s) => s.trAnchorCenter,
    'trMeshColumns': (s) => s.trMeshColumns,
    'trMeshRows': (s) => s.trMeshRows,
    'brBlendLock': (s) => s.brBlendLock,
    'brEditGroup': (s) => s.brEditGroup,
    'brFolderName': (s) => s.brFolderName,
    'brFolderIcon': (s) => s.brFolderIcon,
    'commonReset': (s) => s.commonReset,
    'commonFill': (s) => s.commonFill,
    'viewZoomIn': (s) => s.viewZoomIn,
    'viewZoomOut': (s) => s.viewZoomOut,
    'viewFitToView': (s) => s.viewFitToView,
    'viewResetView': (s) => s.viewResetView,
    'panelSettings': (s) => s.panelSettings,
    'viewRotateLeft': (s) => s.viewRotateLeft,
    'viewRotateRight': (s) => s.viewRotateRight,
    'viewFlipHorizontal': (s) => s.viewFlipHorizontal,
    'viewFlipVertical': (s) => s.viewFlipVertical,
    'viewStraighten': (s) => s.viewStraighten,
    'viewZoomDrag': (s) => s.viewZoomDrag,
    'viewAngleDrag': (s) => s.viewAngleDrag,
    'viewDragDoubleTap': (s) => s.viewDragDoubleTap,
    'viewCanvasColor': (s) => s.viewCanvasColor,
    'viewPasteboardColor': (s) => s.viewPasteboardColor,
    'viewBackdropColor': (s) => s.viewBackdropColor,
    'tlSections': (s) => s.tlSections,
    'tlAllDisplayedLayers': (s) => s.tlAllDisplayedLayers,
    'tlShowAll': (s) => s.tlShowAll,
    'tlHideAll': (s) => s.tlHideAll,
    'tlSoloActiveLayer': (s) => s.tlSoloActiveLayer,
    'tlSoloKind': (s) => s.tlSoloKind,
    'tlSoloColor': (s) => s.tlSoloColor,
    'tlSoloFillReferences': (s) => s.tlSoloFillReferences,
    'tlSoloFxOnRows': (s) => s.tlSoloFxOnRows,
    'tlSoloSheetOnRows': (s) => s.tlSoloSheetOnRows,
    'tlApplyAllFx': (s) => s.tlApplyAllFx,
    'tlBypassAllFx': (s) => s.tlBypassAllFx,
    'tlAllOnTimesheet': (s) => s.tlAllOnTimesheet,
    'tlAllOffTimesheet': (s) => s.tlAllOffTimesheet,
    'tlClearAllMarks': (s) => s.tlClearAllMarks,
    'tlClearAllFillRefs': (s) => s.tlClearAllFillRefs,
    'tlColVisibility': (s) => s.tlColVisibility,
    'tlColLayerKind': (s) => s.tlColLayerKind,
    'tlColOnionSkin': (s) => s.tlColOnionSkin,
    'tlColOpacity': (s) => s.tlColOpacity,
    'tlColBlendMode': (s) => s.tlColBlendMode,
    'tlColFx': (s) => s.tlColFx,
    'tlColMark': (s) => s.tlColMark,
    'tlColFillReference': (s) => s.tlColFillReference,
    'tlColTimesheet': (s) => s.tlColTimesheet,
    'tlOpenOnionPanel': (s) => s.tlOpenOnionPanel,
    'tlLayerMark': (s) => s.tlLayerMark,
    'tlRepeat': (s) => s.tlRepeat,
    'tlRepeatSelection': (s) => s.tlRepeatSelection,
    'tlSeNameTemplate': (s) => s.tlSeNameTemplate,
    'tlAddLayerHeader': (s) => s.tlAddLayerHeader,
    'tlSameAsSelected': (s) => s.tlSameAsSelected,
    'tlKindAnimation': (s) => s.tlKindAnimation,
    'tlKindStoryboard': (s) => s.tlKindStoryboard,
    'tlKindImage': (s) => s.tlKindImage,
    'tlKindText': (s) => s.tlKindText,
    'tlKindAdjustment': (s) => s.tlKindAdjustment,
    'tlKindFolder': (s) => s.tlKindFolder,
    'textCelNewTitle': (s) => s.textCelNewTitle,
    'textCelEditTitle': (s) => s.textCelEditTitle,
    'textCelTextLabel': (s) => s.textCelTextLabel,
    'textCelFontLabel': (s) => s.textCelFontLabel,
    'textCelFontSystem': (s) => s.textCelFontSystem,
    'textCelSizeLabel': (s) => s.textCelSizeLabel,
    'textCelAlignLabel': (s) => s.textCelAlignLabel,
    'textCelAlignLeft': (s) => s.textCelAlignLeft,
    'textCelAlignCenter': (s) => s.textCelAlignCenter,
    'textCelAlignRight': (s) => s.textCelAlignRight,
    'textCelColorLabel': (s) => s.textCelColorLabel,
    'textCelBoldLabel': (s) => s.textCelBoldLabel,
    'textCelOutlineLabel': (s) => s.textCelOutlineLabel,
    'textCelBackgroundLabel': (s) => s.textCelBackgroundLabel,
    'textCelPositionLabel': (s) => s.textCelPositionLabel,
    'seNameTagTitle': (s) => s.seNameTagTitle,
    'seNameTagHint': (s) => s.seNameTagHint,
    'seNameTagPositionLabel': (s) => s.seNameTagPositionLabel,
    'seNameTagBoxLabel': (s) => s.seNameTagBoxLabel,
    'seNameTagSampleName': (s) => s.seNameTagSampleName,
    'seNameTagSampleLine': (s) => s.seNameTagSampleLine,
    'seNameTagReset': (s) => s.seNameTagReset,
    'tlKindSe': (s) => s.tlKindSe,
    'tlKindTransition': (s) => s.tlKindTransition,
    'tlKindCamera': (s) => s.tlKindCamera,
    'tlKindSemanticTemplate': (s) => s.tlKindSemanticTemplate,
    'tlKindInstruction': (s) => s.tlKindInstruction,
    'tlNoriShiro': (s) => s.tlNoriShiro,
    'tlAttachFreeAbove': (s) => s.tlAttachFreeAbove,
    'tlAttachFreeBelow': (s) => s.tlAttachFreeBelow,
    'tlAttachSyncedAbove': (s) => s.tlAttachSyncedAbove,
    'tlAttachSyncedBelow': (s) => s.tlAttachSyncedBelow,
    'tlLayerCommands': (s) => s.tlLayerCommands,
    'tlFrameCommands': (s) => s.tlFrameCommands,
    'tlCut': (s) => s.tlCut,
    'tlLayer': (s) => s.tlLayer,
    'tlFrame': (s) => s.tlFrame,
    'tlDuplicateLayer': (s) => s.tlDuplicateLayer,
    'tlLinkDuplicateLayer': (s) => s.tlLinkDuplicateLayer,
    'tlUnlinkLayer': (s) => s.tlUnlinkLayer,
    'tlRenameLayer': (s) => s.tlRenameLayer,
    'tlCopyLayer': (s) => s.tlCopyLayer,
    'tlDeleteLayer': (s) => s.tlDeleteLayer,
    'tlEffects': (s) => s.tlEffects,
    'tlAddEffectTemplate': (s) => s.tlAddEffectTemplate,
    'tlRemoveEffectTemplate': (s) => s.tlRemoveEffectTemplate,
    'tlDropIntoFolderTemplate': (s) => s.tlDropIntoFolderTemplate,
    'tlDropOutOfFolder': (s) => s.tlDropOutOfFolder,
    'tlDropAttachSyncedTemplate': (s) => s.tlDropAttachSyncedTemplate,
    'tlDropAttachFreeTemplate': (s) => s.tlDropAttachFreeTemplate,
    'tlDropDetachAttach': (s) => s.tlDropDetachAttach,
    'tlDropFolderInAttachFolder': (s) => s.tlDropFolderInAttachFolder,
    'tlDetachLayer': (s) => s.tlDetachLayer,
    'tlCopyFrame': (s) => s.tlCopyFrame,
    'tlPasteLinkedFrame': (s) => s.tlPasteLinkedFrame,
    'tlPasteIndependentFrame': (s) => s.tlPasteIndependentFrame,
    'tlDeleteCell': (s) => s.tlDeleteCell,
    'tlEditInstance': (s) => s.tlEditInstance,
    'tlAdd': (s) => s.tlAdd,
    'tlBlankX': (s) => s.tlBlankX,
    'tlMark': (s) => s.tlMark,
    'tlSetCommasN': (s) => s.tlSetCommasN,
    'tlSetCommaTemplate': (s) => s.tlSetCommaTemplate,
    'tlProjectAudioRate': (s) => s.tlProjectAudioRate,
    'tlCustom': (s) => s.tlCustom,
    'tlShowSeRows': (s) => s.tlShowSeRows,
    'tlShowCameraRows': (s) => s.tlShowCameraRows,
    'tlStoryboardLayer': (s) => s.tlStoryboardLayer,
    'tlPush': (s) => s.tlPush,
    'tlPull': (s) => s.tlPull,
    'sbOneStoryboardRowPerCut': (s) => s.sbOneStoryboardRowPerCut,
    'sbTallerRows': (s) => s.sbTallerRows,
    'sbShorterRows': (s) => s.sbShorterRows,
    'cnConte': (s) => s.cnConte,
    'cnActionColumn': (s) => s.cnActionColumn,
    'cnPreviousPage': (s) => s.cnPreviousPage,
    'cnNextPage': (s) => s.cnNextPage,
    'stagePaperSection': (s) => s.stagePaperSection,
    'stagePasteboardSection': (s) => s.stagePasteboardSection,
    'stagePasteboardExtent': (s) => s.stagePasteboardExtent,
    'stageBackdropSection': (s) => s.stageBackdropSection,
    'stageAlphaLabel': (s) => s.stageAlphaLabel,
    'setCommasTitle': (s) => s.setCommasTitle,
    'setCommasField': (s) => s.setCommasField,
    'projectFpsTitle': (s) => s.projectFpsTitle,
    'projectFpsField': (s) => s.projectFpsField,
  };

  for (final language in AppLanguage.values) {
    test('every string resolves in ${language.name}', () {
      final strings = AppStrings.of(language);
      for (final entry in readers.entries) {
        expect(
          entry.value(strings),
          isNotEmpty,
          reason: '${entry.key} is empty or unresolved in ${language.name}',
        );
      }
    });
  }

  // The shortcut registry resolves by ID, not by getter, so it is checked
  // against the registry itself rather than a hand-listed table — a new
  // action cannot be added without this noticing.
  for (final language in AppLanguage.values) {
    test('every shortcut action and category resolves in ${language.name}', () {
      final strings = AppStrings.of(language);
      for (final definition in editorActionDefinitions) {
        expect(
          strings.shortcutLabel(definition.id, definition.label),
          isNotEmpty,
          reason: '${definition.id} in ${language.name}',
        );
        expect(
          strings.shortcutCategory(definition.category, definition.category),
          isNotEmpty,
          reason: '${definition.category} in ${language.name}',
        );
      }
    });
  }

  test('the reader table covers every getter the class declares', () {
    // Guards the guard: a string added without a line above would otherwise
    // be silently unchecked in the four non-English maps.
    //
    // This used to be `expect(readers, hasLength(<n>))` — a hand-kept number,
    // which meant it could only fail when THIS file changed, never when
    // app_strings.dart gained a getter, which is the one case it exists for.
    // It had drifted 47 getters behind. So it reads the declarations out of
    // the source instead, the way the shortcut half of this file reads the
    // registry: adding a getter and forgetting its line here is now what
    // fails, rather than arithmetic.
    final source = File('lib/src/ui/text/app_strings.dart').readAsStringSync();
    final declared = RegExp(
      r'^  String get ([A-Za-z0-9_]+)',
      multiLine: true,
    ).allMatches(source).map((match) => match.group(1)!).toSet();
    // If the scan ever returns nothing the assertions below pass vacuously,
    // which would be the same silent hole in a new disguise.
    expect(declared, hasLength(greaterThan(400)), reason: 'source scan failed');
    expect(
      declared.difference(readers.keys.toSet()),
      isEmpty,
      reason: 'declared in AppStrings but never read here',
    );
    expect(
      readers.keys.toSet().difference(declared),
      isEmpty,
      reason: 'read here but no longer declared in AppStrings',
    );
  });
}
