import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:anicel/src/models/app_language.dart';
import 'package:anicel/src/ui/shortcuts/editor_action_registry.dart';
import 'package:anicel/src/ui/text/app_strings.dart';

/// The key contract behind the fallback table.
///
/// [AppStrings] resolves each getter through a string key into a per-language
/// map, falling back to English. That buys partial translations at the cost
/// of the compiler no longer checking the key — so this reads EVERY getter in
/// EVERY language. A typo'd key throws here instead of at the one moment a
/// user opens that panel in that language.
void main() {
  final readers = <String, String Function(AppStrings)>{
    'languageSettingsTitle': (s) => s.languageSettingsTitle,
    'programLanguageLabel': (s) => s.programLanguageLabel,
    'notationLanguageLabel': (s) => s.notationLanguageLabel,
    'programLanguageHelp': (s) => s.programLanguageHelp,
    'notationLanguageHelp': (s) => s.notationLanguageHelp,
    'noCutSelected': (s) => s.noCutSelected,
    'pageLabel': (s) => s.pageLabel,
    'continuousLabel': (s) => s.continuousLabel,
    'noticeNoFrameHere': (s) => s.noticeNoFrameHere,
    'noticeLayerNotDrawable': (s) => s.noticeLayerNotDrawable,
    'noticeEditAttachOwner': (s) => s.noticeEditAttachOwner,
    'commonCancel': (s) => s.commonCancel,
    'commonApply': (s) => s.commonApply,
    'commonRefresh': (s) => s.commonRefresh,
    'commonClose': (s) => s.commonClose,
    'commonAffectedFiles': (s) => s.commonAffectedFiles,
    'unsupportedFileTitle': (s) => s.unsupportedFileTitle,
    'unsupportedFileMessageTemplate': (s) => s.unsupportedFileMessageTemplate,
    'commonNotice': (s) => s.commonNotice,
    'tlSharedDeselect': (s) => s.tlSharedDeselect,
    'tlSharedColourEdit': (s) => s.tlSharedColourEdit,
    'exportNoCuts': (s) => s.exportNoCuts,
    'exportQueueEmpty': (s) => s.exportQueueEmpty,
    'exportPresetsEmpty': (s) => s.exportPresetsEmpty,
    'audioOffsetTitle': (s) => s.audioOffsetTitle,
    'audioOffsetHelp': (s) => s.audioOffsetHelp,
    'audioOffsetLabel': (s) => s.audioOffsetLabel,
    'audioUnitFrames': (s) => s.audioUnitFrames,
    'audioDevicesTitle': (s) => s.audioDevicesTitle,
    'audioDevicesHelp': (s) => s.audioDevicesHelp,
    'audioOutputLabel': (s) => s.audioOutputLabel,
    'audioInputLabel': (s) => s.audioInputLabel,
    'audioSystemDefault': (s) => s.audioSystemDefault,
    'audioDeviceDefaultSuffix': (s) => s.audioDeviceDefaultSuffix,
    'audioDeviceMissingSuffix': (s) => s.audioDeviceMissingSuffix,
    'audioSyncInspectorTitle': (s) => s.audioSyncInspectorTitle,
    'recordVoiceTooltip': (s) => s.recordVoiceTooltip,
    'recordVoiceStopTooltip': (s) => s.recordVoiceStopTooltip,
    'recordMicOpenFailed': (s) => s.recordMicOpenFailed,
    'recordMicPermissionDenied': (s) => s.recordMicPermissionDenied,
    'recordSelectSeLane': (s) => s.recordSelectSeLane,
    'recordTakeClipped': (s) => s.recordTakeClipped,
    'recordClipMarkerTooltip': (s) => s.recordClipMarkerTooltip,
    // D26: the crossing-fade refusal warning (red corner marker).
    'tlTransitionCrossingWarning': (s) => s.tlTransitionCrossingWarning,
    'audioMicGainLabel': (s) => s.audioMicGainLabel,
    'audioInputChannelLabel': (s) => s.audioInputChannelLabel,
    'audioInputChannelDevice': (s) => s.audioInputChannelDevice,
    'audioInputChannelMonoMix': (s) => s.audioInputChannelMonoMix,
    'audioInputChannelLeft': (s) => s.audioInputChannelLeft,
    'audioInputChannelRight': (s) => s.audioInputChannelRight,
    'audioClippingNoticeLabel': (s) => s.audioClippingNoticeLabel,
    'audioDenoiseLabel': (s) => s.audioDenoiseLabel,
    'audioInputMeterLabel': (s) => s.audioInputMeterLabel,
    'audioTestSoundLabel': (s) => s.audioTestSoundLabel,
    'audioCountInLabel': (s) => s.audioCountInLabel,
    'audioCueBeepsLabel': (s) => s.audioCueBeepsLabel,
    'audioStreamerLabel': (s) => s.audioStreamerLabel,
    'recordNothingRecording': (s) => s.recordNothingRecording,
    'recordTakeEmpty': (s) => s.recordTakeEmpty,
    'recordPlacementFailed': (s) => s.recordPlacementFailed,
    'recordDroppedFramesTemplate': (s) => s.recordDroppedFramesTemplate,
    'layerAudioTitle': (s) => s.layerAudioTitle,
    'audioGainLabel': (s) => s.audioGainLabel,
    'audioPanLabel': (s) => s.audioPanLabel,
    'layerAudioPanHelp': (s) => s.layerAudioPanHelp,
    'audioMute': (s) => s.audioMute,
    'audioSolo': (s) => s.audioSolo,
    'fpsAudioTitleTemplate': (s) => s.fpsAudioTitleTemplate,
    'fpsAudioBody': (s) => s.fpsAudioBody,
    'fpsAudioKeep': (s) => s.fpsAudioKeep,
    'fpsAudioPull': (s) => s.fpsAudioPull,
    'selectionMoveConfirmTitle': (s) => s.selectionMoveConfirmTitle,
    'selectionMoveConfirmBody': (s) => s.selectionMoveConfirmBody,
    'selectionMoveRevert': (s) => s.selectionMoveRevert,
    'selectionMoveApply': (s) => s.selectionMoveApply,
    'selectionClosePolygon': (s) => s.selectionClosePolygon,
    'commonSave': (s) => s.commonSave,
    'commonDelete': (s) => s.commonDelete,
    'commonRename': (s) => s.commonRename,
    'commonLink': (s) => s.commonLink,
    'commonPreview': (s) => s.commonPreview,
    'renameLayerTitle': (s) => s.renameLayerTitle,
    'renameLayerField': (s) => s.renameLayerField,
    'renameLayerEmpty': (s) => s.renameLayerEmpty,
    'renameCutTitle': (s) => s.renameCutTitle,
    'renameCutField': (s) => s.renameCutField,
    'renameCutEmpty': (s) => s.renameCutEmpty,
    'renameFrameTitle': (s) => s.renameFrameTitle,
    'renameFrameField': (s) => s.renameFrameField,
    'renameKeyTitle': (s) => s.renameKeyTitle,
    'renameKeyField': (s) => s.renameKeyField,
    'renameGuideTitle': (s) => s.renameGuideTitle,
    'renameGuideField': (s) => s.renameGuideField,
    'renameGuideEmpty': (s) => s.renameGuideEmpty,
    'cutNoteTitle': (s) => s.cutNoteTitle,
    'cutNoteField': (s) => s.cutNoteField,
    'deleteLayerTitle': (s) => s.deleteLayerTitle,
    'deleteLayerMessageTemplate': (s) => s.deleteLayerMessageTemplate,
    'frameNameConflictTitle': (s) => s.frameNameConflictTitle,
    'frameNameConflictBody': (s) => s.frameNameConflictBody,
    'seInstanceNewTitle': (s) => s.seInstanceNewTitle,
    'seInstanceEditTitle': (s) => s.seInstanceEditTitle,
    'seNameLabel': (s) => s.seNameLabel,
    'seDialogueLabel': (s) => s.seDialogueLabel,
    'tlResetGroup': (s) => s.tlResetGroup,
    'seNameTagShowLineLabel': (s) => s.seNameTagShowLineLabel,
    'seNameTagLineInkLabel': (s) => s.seNameTagLineInkLabel,
    'seNameTagSizeLabel': (s) => s.seNameTagSizeLabel,
    'seNameTagTrackingLabel': (s) => s.seNameTagTrackingLabel,
    'seNameTagBoldLabel': (s) => s.seNameTagBoldLabel,
    'seNameTagNameInkLabel': (s) => s.seNameTagNameInkLabel,
    'seNameTagBoxColorLabel': (s) => s.seNameTagBoxColorLabel,
    'seNameTagPreviewName': (s) => s.seNameTagPreviewName,
    'seNameTagPreviewLine': (s) => s.seNameTagPreviewLine,
    'seLinkedAudioLabel': (s) => s.seLinkedAudioLabel,
    'seLinkedAudioNone': (s) => s.seLinkedAudioNone,
    'seUnlinkAudio': (s) => s.seUnlinkAudio,
    'keyInterpolationLinear': (s) => s.keyInterpolationLinear,
    'keyInterpolationHold': (s) => s.keyInterpolationHold,
    'convertLinkedCutTitle': (s) => s.convertLinkedCutTitle,
    'convertLinkedCutBodyTemplate': (s) => s.convertLinkedCutBodyTemplate,
    'convertLinkedCutTargetLabel': (s) => s.convertLinkedCutTargetLabel,
    'convertLinkedCutLinksTemplate': (s) => s.convertLinkedCutLinksTemplate,
    'convertLinkedCutReplacedTemplate': (s) =>
        s.convertLinkedCutReplacedTemplate,
    'convertLinkedCutJoiningTemplate': (s) => s.convertLinkedCutJoiningTemplate,
    'convertLinkedCutTargetGainsTemplate': (s) =>
        s.convertLinkedCutTargetGainsTemplate,
    'convertLinkedCutOriginGainsTemplate': (s) =>
        s.convertLinkedCutOriginGainsTemplate,
    'convertLinkedCutNothing': (s) => s.convertLinkedCutNothing,
    'convertLinkedCutUndoNote': (s) => s.convertLinkedCutUndoNote,
    'convertLinkedCutResizeFirst': (s) => s.convertLinkedCutResizeFirst,
    'guideKindSymmetry': (s) => s.guideKindSymmetry,
    'guideKindPerspective': (s) => s.guideKindPerspective,
    'guideAdd': (s) => s.guideAdd,
    'guideDelete': (s) => s.guideDelete,
    'guideShow': (s) => s.guideShow,
    'guideActsOn': (s) => s.guideActsOn,
    'guideActsOff': (s) => s.guideActsOff,
    'guideLibraryEmpty': (s) => s.guideLibraryEmpty,
    'noGuideSelected': (s) => s.noGuideSelected,
    'guideLineCount': (s) => s.guideLineCount,
    'guideMirrorMode': (s) => s.guideMirrorMode,
    'guideMirrorModeOn': (s) => s.guideMirrorModeOn,
    'guideMirrorModeOff': (s) => s.guideMirrorModeOff,
    'guideEyeLevelShow': (s) => s.guideEyeLevelShow,
    'guideConstrainToEyeLevel': (s) => s.guideConstrainToEyeLevel,
    'guideConstrainToEyeLevelNote': (s) => s.guideConstrainToEyeLevelNote,
    'guideVanishingPoint': (s) => s.guideVanishingPoint,
    'guideVanishingPointAtInfinity': (s) => s.guideVanishingPointAtInfinity,
    'guideAddVanishingPoint': (s) => s.guideAddVanishingPoint,
    'guideMakeVertical': (s) => s.guideMakeVertical,
    'closeProjectTitle': (s) => s.closeProjectTitle,
    'closeProjectBody': (s) => s.closeProjectBody,
    'closeProjectVanishedBody': (s) => s.closeProjectVanishedBody,
    'commonSaveAs': (s) => s.commonSaveAs,
    'saveProgressRunning': (s) => s.saveProgressRunning,
    'saveProgressDone': (s) => s.saveProgressDone,
    'savePrepareRunning': (s) => s.savePrepareRunning,
    'savePrepareDone': (s) => s.savePrepareDone,
    'openProgressRunning': (s) => s.openProgressRunning,
    'openProgressDone': (s) => s.openProgressDone,
    'openWaitingCloudTemplate': (s) => s.openWaitingCloudTemplate,
    'openWaitingStalledTemplate': (s) => s.openWaitingStalledTemplate,
    'resizeProgressRunning': (s) => s.resizeProgressRunning,
    'resizeProgressDone': (s) => s.resizeProgressDone,
    'unsavedAutosaveTitle': (s) => s.unsavedAutosaveTitle,
    'unsavedAutosaveBody': (s) => s.unsavedAutosaveBody,
    'commonNotNow': (s) => s.commonNotNow,
    'menuBarFile': (s) => s.menuBarFile,
    'menuBarEdit': (s) => s.menuBarEdit,
    'menuBarCut': (s) => s.menuBarCut,
    'menuBarLayer': (s) => s.menuBarLayer,
    'menuBarPlayback': (s) => s.menuBarPlayback,
    'menuBarWindow': (s) => s.menuBarWindow,
    'menuBarHelp': (s) => s.menuBarHelp,
    'menuPlay': (s) => s.menuPlay,
    'menuPause': (s) => s.menuPause,
    'menuAlphaPreview': (s) => s.menuAlphaPreview,
    'topStripProject': (s) => s.topStripProject,
    'topStripSettings': (s) => s.topStripSettings,
    'fileOpenTitle': (s) => s.fileOpenTitle,
    'fileSaveTitle': (s) => s.fileSaveTitle,
    'fileStorageOffNotice': (s) => s.fileStorageOffNotice,
    'fileOpenSettings': (s) => s.fileOpenSettings,
    'fileNameLabel': (s) => s.fileNameLabel,
    'fileCloudNoticeOpen': (s) => s.fileCloudNoticeOpen,
    'replaceFileTitle': (s) => s.replaceFileTitle,
    'replaceFileMessageTemplate': (s) => s.replaceFileMessageTemplate,
    'commonReplace': (s) => s.commonReplace,
    'folderNoPathTitle': (s) => s.folderNoPathTitle,
    'folderStorageOffTitle': (s) => s.folderStorageOffTitle,
    'folderPickUnavailable': (s) => s.folderPickUnavailable,
    'folderPickDriveNotice': (s) => s.folderPickDriveNotice,
    'fileNameEmpty': (s) => s.fileNameEmpty,
    'recentProjectsTitle': (s) => s.recentProjectsTitle,
    'recentReconnect': (s) => s.recentReconnect,
    'sortByName': (s) => s.sortByName,
    'sortByModified': (s) => s.sortByModified,
    'sortBySize': (s) => s.sortBySize,
    'sortAscending': (s) => s.sortAscending,
    'sortDescending': (s) => s.sortDescending,
    'canvasSizeTitle': (s) => s.canvasSizeTitle,
    'cameraSizeTitle': (s) => s.cameraSizeTitle,
    'canvasWidthLabel': (s) => s.canvasWidthLabel,
    'canvasHeightLabel': (s) => s.canvasHeightLabel,
    'canvasAnchorHelpTemplate': (s) => s.canvasAnchorHelpTemplate,
    'canvasPresetDefault': (s) => s.canvasPresetDefault,
    'commonResize': (s) => s.commonResize,
    'inputTitle': (s) => s.inputTitle,
    'inputPressureHeading': (s) => s.inputPressureHeading,
    'inputPressureSoftHard': (s) => s.inputPressureSoftHard,
    'inputPressureLinear': (s) => s.inputPressureLinear,
    'inputSpeedHeading': (s) => s.inputSpeedHeading,
    'inputSpeedReference': (s) => s.inputSpeedReference,
    'inputCanvasHeading': (s) => s.inputCanvasHeading,
    'inputRightClick': (s) => s.inputRightClick,
    'inputWheelClick': (s) => s.inputWheelClick,
    'inputCanvasTouchHeading': (s) => s.inputCanvasTouchHeading,
    'inputDragOneFinger': (s) => s.inputDragOneFinger,
    'inputDragTwoFingers': (s) => s.inputDragTwoFingers,
    'inputDragThreeFingers': (s) => s.inputDragThreeFingers,
    'inputExtraFinger': (s) => s.inputExtraFinger,
    'inputExtraFingerHelp': (s) => s.inputExtraFingerHelp,
    'inputTwoFingerRotation': (s) => s.inputTwoFingerRotation,
    'inputTwoFingerRotationHelp': (s) => s.inputTwoFingerRotationHelp,
    'inputRotationLock': (s) => s.inputRotationLock,
    'inputRotationLockHelp': (s) => s.inputRotationLockHelp,
    'inputRotationSnap': (s) => s.inputRotationSnap,
    'inputZoomSnaps': (s) => s.inputZoomSnaps,
    'inputBrushSizeSnaps': (s) => s.inputBrushSizeSnaps,
    'inputTabletHeading': (s) => s.inputTabletHeading,
    'inputTabletStandard': (s) => s.inputTabletStandard,
    'inputTabletStandardHelp': (s) => s.inputTabletStandardHelp,
    'inputTabletWintab': (s) => s.inputTabletWintab,
    'inputTabletWintabHelp': (s) => s.inputTabletWintabHelp,
    'inputTabletAutoDemoted': (s) => s.inputTabletAutoDemoted,
    'inputPenTail': (s) => s.inputPenTail,
    'inputFlipHaptics': (s) => s.inputFlipHaptics,
    'inputFlipHapticsHelp': (s) => s.inputFlipHapticsHelp,
    'dragActionFlip': (s) => s.dragActionFlip,
    'dragActionScreen': (s) => s.dragActionScreen,
    'dragActionBrushSize': (s) => s.dragActionBrushSize,
    'dragActionDraw': (s) => s.dragActionDraw,
    'commonNone': (s) => s.commonNone,
    'mapEyedropper': (s) => s.mapEyedropper,
    'mapEraser': (s) => s.mapEraser,
    'mapPan': (s) => s.mapPan,
    'mapUndo': (s) => s.mapUndo,
    'mapRedo': (s) => s.mapRedo,
    'holdReturnToTool': (s) => s.holdReturnToTool,
    'holdKeep': (s) => s.holdKeep,
    'prefsTitle': (s) => s.prefsTitle,
    'prefsInput': (s) => s.prefsInput,
    'prefsAutosave': (s) => s.prefsAutosave,
    'prefsAudio': (s) => s.prefsAudio,
    'prefsLanguage': (s) => s.prefsLanguage,
    'prefsAccent': (s) => s.prefsAccent,
    'prefsDisplay': (s) => s.prefsDisplay,
    'prefsSystem': (s) => s.prefsSystem,
    'prefsMemory': (s) => s.prefsMemory,
    'memoryProcessTotal': (s) => s.memoryProcessTotal,
    'memoryTracked': (s) => s.memoryTracked,
    'memoryUntracked': (s) => s.memoryUntracked,
    'memoryAvailable': (s) => s.memoryAvailable,
    'memoryPinned': (s) => s.memoryPinned,
    'memoryDeviceTotal': (s) => s.memoryDeviceTotal,
    'memoryAllowance': (s) => s.memoryAllowance,
    'memoryAllowanceAutomatic': (s) => s.memoryAllowanceAutomatic,
    'memoryItemDrawings': (s) => s.memoryItemDrawings,
    'memoryItemSheetInk': (s) => s.memoryItemSheetInk,
    'memoryItemUndo': (s) => s.memoryItemUndo,
    'memoryItemPlaybackFrames': (s) => s.memoryItemPlaybackFrames,
    'memoryItemLayerImages': (s) => s.memoryItemLayerImages,
    'memoryItemBrushTips': (s) => s.memoryItemBrushTips,
    'memoryItemPanelRasters': (s) => s.memoryItemPanelRasters,
    'memoryItemViewerPages': (s) => s.memoryItemViewerPages,
    'memoryItemImageCache': (s) => s.memoryItemImageCache,
    'memoryItemStoryboardThumbnails': (s) => s.memoryItemStoryboardThumbnails,
    'memoryItemMoviePictures': (s) => s.memoryItemMoviePictures,
    'memoryItemTileImages': (s) => s.memoryItemTileImages,
    'memoryItemEnginePool': (s) => s.memoryItemEnginePool,
    'memoryItemEngineScratch': (s) => s.memoryItemEngineScratch,
    'containerAreaSettings': (s) => s.containerAreaSettings,
    'containerAreaDiagnostics': (s) => s.containerAreaDiagnostics,
    'containerAreaSessionScratch': (s) => s.containerAreaSessionScratch,
    'containerTotal': (s) => s.containerTotal,
    'saveCelsLostTemplate': (s) => s.saveCelsLostTemplate,
    'saveCelsLostHeading': (s) => s.saveCelsLostHeading,
    'saveCelsLostGone': (s) => s.saveCelsLostGone,
    // R11: the interface scale, in the Display section.
    'uiScaleLabel': (s) => s.uiScaleLabel,
    'accentTitle': (s) => s.accentTitle,
    'accent1Label': (s) => s.accent1Label,
    'accent1Help': (s) => s.accent1Help,
    'sheetInfoTitle': (s) => s.sheetInfoTitle,
    'sheetFieldTitle': (s) => s.sheetFieldTitle,
    'sheetFieldEpisode': (s) => s.sheetFieldEpisode,
    'sheetFieldScene': (s) => s.sheetFieldScene,
    'sheetFieldCut': (s) => s.sheetFieldCut,
    'sheetFieldTime': (s) => s.sheetFieldTime,
    'sheetFieldName': (s) => s.sheetFieldName,
    'sheetFieldSheet': (s) => s.sheetFieldSheet,
    'sheetTitleHint': (s) => s.sheetTitleHint,
    'sheetArtist': (s) => s.sheetArtist,
    'sheetStaffByProcess': (s) => s.sheetStaffByProcess,
    'sheetVisibleBoxes': (s) => s.sheetVisibleBoxes,
    'sheetStampPick': (s) => s.sheetStampPick,
    'sheetStampClear': (s) => s.sheetStampClear,
    'sheetNotation': (s) => s.sheetNotation,
    'sheetExposureBar': (s) => s.sheetExposureBar,
    'sheetExposureBarHelp': (s) => s.sheetExposureBarHelp,
    'sheetExposureBarN': (s) => s.sheetExposureBarN,
    'sheetSeEmptyFill': (s) => s.sheetSeEmptyFill,
    'sheetInkBlock': (s) => s.sheetInkBlock,
    'sheetInkAllow': (s) => s.sheetInkAllow,
    'sheetModeNotation': (s) => s.sheetModeNotation,
    'sheetModeData': (s) => s.sheetModeData,
    'sheetViewPage': (s) => s.sheetViewPage,
    'sheetViewContinuous': (s) => s.sheetViewContinuous,
    'instructionsTitle': (s) => s.instructionsTitle,
    'instructionEditTooltip': (s) => s.instructionEditTooltip,
    'instructionDeleteTooltip': (s) => s.instructionDeleteTooltip,
    'instructionAddButton': (s) => s.instructionAddButton,
    'instructionDefTitle': (s) => s.instructionDefTitle,
    'instructionDefNameLabel': (s) => s.instructionDefNameLabel,
    'instructionEventEditTitle': (s) => s.instructionEventEditTitle,
    'instructionEventAddTitle': (s) => s.instructionEventAddTitle,
    'instructionMarkLabel': (s) => s.instructionMarkLabel,
    'instructionNameLabel': (s) => s.instructionNameLabel,
    'instructionStartLabel': (s) => s.instructionStartLabel,
    'instructionEndLabel': (s) => s.instructionEndLabel,
    'instructionMemoLabel': (s) => s.instructionMemoLabel,
    'instructionEditSetButton': (s) => s.instructionEditSetButton,
    'instructionEditorIcon': (s) => s.instructionEditorIcon,
    'instructionEditorColor': (s) => s.instructionEditorColor,
    'instructionEditorMark': (s) => s.instructionEditorMark,
    'systemStatusHelp': (s) => s.systemStatusHelp,
    'cutCommands': (s) => s.cutCommands,
    'cutAddCut': (s) => s.cutAddCut,
    'cutNewCut': (s) => s.cutNewCut,
    'cutDuplicateCut': (s) => s.cutDuplicateCut,
    'cutDuplicateActive': (s) => s.cutDuplicateActive,
    'cutRename': (s) => s.cutRename,
    'cutEditNote': (s) => s.cutEditNote,
    'cutMoveLeft': (s) => s.cutMoveLeft,
    'cutMoveRight': (s) => s.cutMoveRight,
    'cutDelete': (s) => s.cutDelete,
    'mediaActions': (s) => s.mediaActions,
    'mediaPoolEmpty': (s) => s.mediaPoolEmpty,
    'mediaImportAudio': (s) => s.mediaImportAudio,
    'mediaRename': (s) => s.mediaRename,
    'mediaPlace': (s) => s.mediaPlace,
    'mediaRelink': (s) => s.mediaRelink,
    'mediaMissingCount': (s) => s.mediaMissingCount,
    'mediaFindInFolder': (s) => s.mediaFindInFolder,
    'mediaRelinkFound': (s) => s.mediaRelinkFound,
    'mediaRelinkScanning': (s) => s.mediaRelinkScanning,
    'mediaRelinkScanned': (s) => s.mediaRelinkScanned,
    'mediaRemove': (s) => s.mediaRemove,
    'mediaRegisterInProject': (s) => s.mediaRegisterInProject,
    'mediaCarriedState': (s) => s.mediaCarriedState,
    'mediaReferencedState': (s) => s.mediaReferencedState,
    'tlLayerReference': (s) => s.tlLayerReference,
    'tlSelectedLayers': (s) => s.tlSelectedLayers,
    'layerRasterizeLabel': (s) => s.layerRasterizeLabel,
    'exCelCountOne': (s) => s.exCelCountOne,
    'projectFileVanished': (s) => s.projectFileVanished,
    'mediaExportWav': (s) => s.mediaExportWav,
    'mediaExportWavNoAudio': (s) => s.mediaExportWavNoAudio,
    'projectLegacyAssetsFolder': (s) => s.projectLegacyAssetsFolder,
    'mediaRemoveInUse': (s) => s.mediaRemoveInUse,
    'mediaUsesHeading': (s) => s.mediaUsesHeading,
    'mediaOpenInViewer': (s) => s.mediaOpenInViewer,
    'mediaOpenInSubViewer': (s) => s.mediaOpenInSubViewer,
    'mediaViewerEmpty': (s) => s.mediaViewerEmpty,
    'mediaViewerOpenFile': (s) => s.mediaViewerOpenFile,
    'mediaViewerLoadFailed': (s) => s.mediaViewerLoadFailed,
    'mediaViewerCutTooLarge': (s) => s.mediaViewerCutTooLarge,
    'mediaViewerCannotDisplay': (s) => s.mediaViewerCannotDisplay,
    'mediaViewerNoPdfRenderer': (s) => s.mediaViewerNoPdfRenderer,
    'mediaViewerNoVideoDecoder': (s) => s.mediaViewerNoVideoDecoder,
    'mediaViewerNoAudioDecoder': (s) => s.mediaViewerNoAudioDecoder,
    'mediaViewerSwap': (s) => s.mediaViewerSwap,
    'mediaViewerRegisterAsset': (s) => s.mediaViewerRegisterAsset,
    'panelCanvas': (s) => s.panelCanvas,
    'panelColorWheel': (s) => s.panelColorWheel,
    'panelColorRgb': (s) => s.panelColorRgb,
    'panelColorPalette': (s) => s.panelColorPalette,
    'transportIn': (s) => s.transportIn,
    'transportOut': (s) => s.transportOut,
    'transportLoop': (s) => s.transportLoop,
    'transportPrevFrame': (s) => s.transportPrevFrame,
    'transportNextFrame': (s) => s.transportNextFrame,
    'colorRecent': (s) => s.colorRecent,
    'colorBackgroundSwap': (s) => s.colorBackgroundSwap,
    'penPressureTitle': (s) => s.penPressureTitle,
    'penPressureAxis': (s) => s.penPressureAxis,
    'brushDynamicsTitle': (s) => s.brushDynamicsTitle,
    'curveSourcePressure': (s) => s.curveSourcePressure,
    'curveSourceTilt': (s) => s.curveSourceTilt,
    'curveSourceSpeed': (s) => s.curveSourceSpeed,
    'onionCurrentDrawing': (s) => s.onionCurrentDrawing,
    'audioLevelMeter': (s) => s.audioLevelMeter,
    'panelMedia': (s) => s.panelMedia,
    'panelMediaViewer': (s) => s.panelMediaViewer,
    'panelMediaViewerSub': (s) => s.panelMediaViewerSub,
    'panelOnionSkin': (s) => s.panelOnionSkin,
    'panelToolSize': (s) => s.panelToolSize,
    'panelStoryboard': (s) => s.panelStoryboard,
    'panelTimeline': (s) => s.panelTimeline,
    'panelTimesheet': (s) => s.panelTimesheet,
    'panelConte': (s) => s.panelConte,
    'panelEnvelope': (s) => s.panelEnvelope,
    'commonRegister': (s) => s.commonRegister,
    'commonNameField': (s) => s.commonNameField,
    'tipRegisterTitle': (s) => s.tipRegisterTitle,
    'panelToolLibrary': (s) => s.panelToolLibrary,
    'panelCollapseRegion': (s) => s.panelCollapseRegion,
    'panelNewGroup': (s) => s.panelNewGroup,
    'panelRegionWidth': (s) => s.panelRegionWidth,
    'panelExpandRegion': (s) => s.panelExpandRegion,
    'panelToolSettings': (s) => s.panelToolSettings,
    'panelTools': (s) => s.panelTools,
    'onionBefore': (s) => s.onionBefore,
    'onionAfter': (s) => s.onionAfter,
    'onionBeforeTint': (s) => s.onionBeforeTint,
    'onionAfterTint': (s) => s.onionAfterTint,
    'onionGhostColorHelp': (s) => s.onionGhostColorHelp,
    'onionPegCountHelp': (s) => s.onionPegCountHelp,
    'shortcutTitle': (s) => s.shortcutTitle,
    'shortcutResetAll': (s) => s.shortcutResetAll,
    'shortcutResetToDefault': (s) => s.shortcutResetToDefault,
    'shortcutRecordNew': (s) => s.shortcutRecordNew,
    'shortcutTouch': (s) => s.shortcutTouch,
    'shortcutSearch': (s) => s.shortcutSearch,
    'shortcutConflictBanner': (s) => s.shortcutConflictBanner,
    'shortcutRecordingHint': (s) => s.shortcutRecordingHint,
    'playbackQuality': (s) => s.playbackQuality,
    'playbackStop': (s) => s.playbackStop,
    'playbackToStart': (s) => s.playbackToStart,
    'sheetPreviousPage': (s) => s.sheetPreviousPage,
    'sheetNextPage': (s) => s.sheetNextPage,
    'sheetPageDrag': (s) => s.sheetPageDrag,
    'autosaveTitle': (s) => s.autosaveTitle,
    'autosaveEvery': (s) => s.autosaveEvery,
    'autosaveSectionHelp': (s) => s.autosaveSectionHelp,
    'autosaveSwitchHelp': (s) => s.autosaveSwitchHelp,
    'appContainerTitle': (s) => s.appContainerTitle,
    'appContainerHelp': (s) => s.appContainerHelp,
    'commonMinutesShort': (s) => s.commonMinutesShort,
    'exExport': (s) => s.exExport,
    'exAddToQueue': (s) => s.exAddToQueue,
    'exImage': (s) => s.exImage,
    'exVideo': (s) => s.exVideo,
    'exCels': (s) => s.exCels,
    'exSheetPng': (s) => s.exSheetPng,
    'exFormat': (s) => s.exFormat,
    'exOptions': (s) => s.exOptions,
    'exNaming': (s) => s.exNaming,
    'exScope': (s) => s.exScope,
    'exQuality': (s) => s.exQuality,
    'exCodec': (s) => s.exCodec,
    'exBitrate': (s) => s.exBitrate,
    'exChannels': (s) => s.exChannels,
    'exAudio': (s) => s.exAudio,
    'exBrowse': (s) => s.exBrowse,
    'exSavePreset': (s) => s.exSavePreset,
    'exPresetNameEmpty': (s) => s.exPresetNameEmpty,
    'exBaseName': (s) => s.exBaseName,
    'exSuffix': (s) => s.exSuffix,
    'exDigits': (s) => s.exDigits,
    'exApplyLayerFx': (s) => s.exApplyLayerFx,
    'exApplyLayerFxHelp': (s) => s.exApplyLayerFxHelp,
    'exMuxSeMix': (s) => s.exMuxSeMix,
    'exLabel': (s) => s.exLabel,
    'exApply': (s) => s.exApply,
    'exAdd': (s) => s.exAdd,
    'exSelect': (s) => s.exSelect,
    'exSelBase': (s) => s.exSelBase,
    'exSelAttach': (s) => s.exSelAttach,
    'exSelSheet': (s) => s.exSelSheet,
    'exSelDirection': (s) => s.exSelDirection,
    'exSelCustom': (s) => s.exSelCustom,
    'exPaperLabel': (s) => s.exPaperLabel,
    'exArtLabel': (s) => s.exArtLabel,
    'exTakeLatest': (s) => s.exTakeLatest,
    'exFolders': (s) => s.exFolders,
    'exNameParts': (s) => s.exNameParts,
    'exTarget': (s) => s.exTarget,
    'exLayer': (s) => s.exLayer,
    'exProject': (s) => s.exProject,
    'exCut': (s) => s.exCut,
    'exWhite': (s) => s.exWhite,
    'exBlack': (s) => s.exBlack,
    'exBackground': (s) => s.exBackground,
    'exChooseLocation': (s) => s.exChooseLocation,
    'exNoCels': (s) => s.exNoCels,
    'exNoCuts': (s) => s.exNoCuts,
    'exPresets': (s) => s.exPresets,
    'exQueue': (s) => s.exQueue,
    'exSize': (s) => s.exSize,
    'exForm': (s) => s.exForm,
    'exCutSize': (s) => s.exCutSize,
    'exRealSheet': (s) => s.exRealSheet,
    'exWidth': (s) => s.exWidth,
    'exSheetLayers': (s) => s.exSheetLayers,
    'exContent': (s) => s.exContent,
    'exInk': (s) => s.exInk,
    'exFiles': (s) => s.exFiles,
    'exOneImage': (s) => s.exOneImage,
    'exOnePerLayer': (s) => s.exOnePerLayer,
    'exCancelled': (s) => s.exCancelled,
    'exNothingInFrame': (s) => s.exNothingInFrame,
    'exExporting': (s) => s.exExporting,
    'exRenderingQueue': (s) => s.exRenderingQueue,
    'exTransparent': (s) => s.exTransparent,
    'exOpaque': (s) => s.exOpaque,
    'exEnvelopePaperCut': (s) => s.exEnvelopePaperCut,
    'exFileLabel': (s) => s.exFileLabel,
    'exPatternLabel': (s) => s.exPatternLabel,
    'exLocationLabel': (s) => s.exLocationLabel,
    'exChooseFolder': (s) => s.exChooseFolder,
    'exVectorPdf': (s) => s.exVectorPdf,
    'exPagePng': (s) => s.exPagePng,
    'exFxOn': (s) => s.exFxOn,
    'exFxOff': (s) => s.exFxOff,
    'exTabSequence': (s) => s.exTabSequence,
    'exSizeCamera': (s) => s.exSizeCamera,
    'exSizeCanvas': (s) => s.exSizeCanvas,
    'exSheetImage': (s) => s.exSheetImage,
    'exPageImage': (s) => s.exPageImage,
    'exSaveCurrent': (s) => s.exSaveCurrent,
    'exRenderQueue': (s) => s.exRenderQueue,
    'exRenderAll': (s) => s.exRenderAll,
    'exJobQueued': (s) => s.exJobQueued,
    'exJobDone': (s) => s.exJobDone,
    'exJobFailed': (s) => s.exJobFailed,
    'exJobCancelled': (s) => s.exJobCancelled,
    'exIncludeAll': (s) => s.exIncludeAll,
    'exNeedsFfmpeg': (s) => s.exNeedsFfmpeg,
    'exCheckingEncoders': (s) => s.exCheckingEncoders,
    'exNotInThisBuild': (s) => s.exNotInThisBuild,
    'exBitrateAuto': (s) => s.exBitrateAuto,
    'exCanvasTemplate': (s) => s.exCanvasTemplate,
    'exCanvasPerCut': (s) => s.exCanvasPerCut,
    'imNotTvpp': (s) => s.imNotTvpp,
    'imFileUnreadable': (s) => s.imFileUnreadable,

    'imImport': (s) => s.imImport,
    'imPool': (s) => s.imPool,
    'imFile': (s) => s.imFile,
    'imFiles': (s) => s.imFiles,
    'imInto': (s) => s.imInto,
    'imFit': (s) => s.imFit,
    'imRevisions': (s) => s.imRevisions,
    'imFilesButton': (s) => s.imFilesButton,
    'imCutFolderButton': (s) => s.imCutFolderButton,
    'imModified': (s) => s.imModified,
    'imSize': (s) => s.imSize,
    'imArchivedProcesses': (s) => s.imArchivedProcesses,
    'imMultiCutFolders': (s) => s.imMultiCutFolders,
    'imProcess': (s) => s.imProcess,
    'imPicture': (s) => s.imPicture,
    'imReference': (s) => s.imReference,
    'imExcluded': (s) => s.imExcluded,
    'imIgnored': (s) => s.imIgnored,
    'imMultiCutMark': (s) => s.imMultiCutMark,
    'imPickToSee': (s) => s.imPickToSee,
    'imPlaceLabel': (s) => s.imPlaceLabel,
    'imPoolOnlyTooltip': (s) => s.imPoolOnlyTooltip,
    'imAlreadyPooledTooltip': (s) => s.imAlreadyPooledTooltip,
    'imModeKeep': (s) => s.imModeKeep,
    'imModeReference': (s) => s.imModeReference,
    'imBake': (s) => s.imBake,
    'commonOn': (s) => s.commonOn,
    'commonOff': (s) => s.commonOff,
    'imFitContain': (s) => s.imFitContain,
    'imFitStretch': (s) => s.imFitStretch,
    'imIntoNewLayer': (s) => s.imIntoNewLayer,
    'imIntoSeRow': (s) => s.imIntoSeRow,
    'imIntoNewCut': (s) => s.imIntoNewCut,
    'imPsdMerge': (s) => s.imPsdMerge,
    'imPsdExpand': (s) => s.imPsdExpand,
    'imNoSource': (s) => s.imNoSource,
    'imStatusImporting': (s) => s.imStatusImporting,
    'imStatusNothing': (s) => s.imStatusNothing,
    'imFolderGone': (s) => s.imFolderGone,
    'imCutFolderUnreadable': (s) => s.imCutFolderUnreadable,
    'imKeepExplain': (s) => s.imKeepExplain,
    'imReferenceExplain': (s) => s.imReferenceExplain,
    'imCutFolderBakes': (s) => s.imCutFolderBakes,
    'imRevLatest': (s) => s.imRevLatest,
    'imRevAll': (s) => s.imRevAll,
    'imRevOriginals': (s) => s.imRevOriginals,
    'imSound': (s) => s.imSound,
    'bakeProgressRunning': (s) => s.bakeProgressRunning,
    'bakeProgressDone': (s) => s.bakeProgressDone,
    'mpFileMissing': (s) => s.mpFileMissing,
    'mpInUseOnTimeline': (s) => s.mpInUseOnTimeline,
    'mpNameEmpty': (s) => s.mpNameEmpty,
    'exCameraTemplate': (s) => s.exCameraTemplate,
    'toolBrush': (s) => s.toolBrush,
    'toolEraser': (s) => s.toolEraser,
    'toolEyedropper': (s) => s.toolEyedropper,
    'toolFill': (s) => s.toolFill,
    'toolSelect': (s) => s.toolSelect,
    'toolTransform': (s) => s.toolTransform,
    'toolShapeFill': (s) => s.toolShapeFill,
    'toolCutNothingHeld': (s) => s.toolCutNothingHeld,
    'toolLibraryEmpty': (s) => s.toolLibraryEmpty,
    'toolCutPasteAtOrigin': (s) => s.toolCutPasteAtOrigin,
    'toolCutFlipHorizontal': (s) => s.toolCutFlipHorizontal,
    'toolCutFlipVertical': (s) => s.toolCutFlipVertical,
    'toolCutRegisterTip': (s) => s.toolCutRegisterTip,
    'toolEyedropperReference': (s) => s.toolEyedropperReference,
    'brushSettingsTitle': (s) => s.brushSettingsTitle,
    'toolShapeRect': (s) => s.toolShapeRect,
    'toolShapeEllipse': (s) => s.toolShapeEllipse,
    'toolShapeLasso': (s) => s.toolShapeLasso,
    'toolShapePolygon': (s) => s.toolShapePolygon,
    'toolShapeSelectTemplate': (s) => s.toolShapeSelectTemplate,
    'toolShapeCutTemplate': (s) => s.toolShapeCutTemplate,
    'toolShapeFillTemplate': (s) => s.toolShapeFillTemplate,
    'brBrushesTitle': (s) => s.brBrushesTitle,
    'brNewGroup': (s) => s.brNewGroup,
    'brNewGroupName': (s) => s.brNewGroupName,
    'brNewPresetName': (s) => s.brNewPresetName,
    'brGroupNameField': (s) => s.brGroupNameField,
    'brCreate': (s) => s.brCreate,
    'brRenameBrush': (s) => s.brRenameBrush,
    'brBrushNameField': (s) => s.brBrushNameField,
    'brGroupNameEmpty': (s) => s.brGroupNameEmpty,
    'brBrushNameEmpty': (s) => s.brBrushNameEmpty,
    'brResetLibraryBody': (s) => s.brResetLibraryBody,
    'brRenameTip': (s) => s.brRenameTip,
    'brDeleteTip': (s) => s.brDeleteTip,
    'brSize': (s) => s.brSize,
    'brOpacity': (s) => s.brOpacity,
    'brFlow': (s) => s.brFlow,
    'brHardness': (s) => s.brHardness,
    'stepUp': (s) => s.stepUp,
    'stepDown': (s) => s.stepDown,
    'brEdge': (s) => s.brEdge,
    'brEdgeNone': (s) => s.brEdgeNone,
    'brSpacing': (s) => s.brSpacing,
    'brAngle': (s) => s.brAngle,
    'brRoundness': (s) => s.brRoundness,
    'brScale': (s) => s.brScale,
    'brStabilizer': (s) => s.brStabilizer,
    'brBlend': (s) => s.brBlend,
    'brBlendMode': (s) => s.brBlendMode,
    'brDualBlend': (s) => s.brDualBlend,
    'brFeather': (s) => s.brFeather,
    'brTolerance': (s) => s.brTolerance,
    'brGapClose': (s) => s.brGapClose,
    'brGrowShrink': (s) => s.brGrowShrink,
    'brAntiAlias': (s) => s.brAntiAlias,
    'brAntiAliasEdge': (s) => s.brAntiAliasEdge,
    'brTransformPreserveColors': (s) => s.brTransformPreserveColors,
    'brTransformPreserveColorsHint': (s) => s.brTransformPreserveColorsHint,
    'brFillBeyondCanvas': (s) => s.brFillBeyondCanvas,
    'brOpenRegionsRefuse': (s) => s.brOpenRegionsRefuse,
    'brName': (s) => s.brName,
    'brDisplay': (s) => s.brDisplay,
    'brTipIcon': (s) => s.brTipIcon,
    'brStrokePreview': (s) => s.brStrokePreview,
    'brBrushOptions': (s) => s.brBrushOptions,
    'brGroupOptions': (s) => s.brGroupOptions,
    'brRenameGroup': (s) => s.brRenameGroup,
    'brDeleteGroup': (s) => s.brDeleteGroup,
    'brRenameSelected': (s) => s.brRenameSelected,
    'brDeleteSelected': (s) => s.brDeleteSelected,
    'brSaveAsPreset': (s) => s.brSaveAsPreset,
    'brImportBrushes': (s) => s.brImportBrushes,
    'brResetLibrary': (s) => s.brResetLibrary,
    'brExportSelected': (s) => s.brExportSelected,
    'brExportGroup': (s) => s.brExportGroup,
    'brExportNothing': (s) => s.brExportNothing,
    'brExpand': (s) => s.brExpand,
    'brBrushTip': (s) => s.brBrushTip,
    'brTipNone': (s) => s.brTipNone,
    'brAddTipImage': (s) => s.brAddTipImage,
    'brTipRotation': (s) => s.brTipRotation,
    'brRotationFixed': (s) => s.brRotationFixed,
    'brRotationDirection': (s) => s.brRotationDirection,
    'brDualTip': (s) => s.brDualTip,
    'brTexture': (s) => s.brTexture,
    'brTextureDensity': (s) => s.brTextureDensity,
    'brTextureInvert': (s) => s.brTextureInvert,
    'brTextureBrightness': (s) => s.brTextureBrightness,
    'brTextureContrast': (s) => s.brTextureContrast,
    'brScatter': (s) => s.brScatter,
    'brScatterCount': (s) => s.brScatterCount,
    'brScatterBothAxes': (s) => s.brScatterBothAxes,
    'brSizeJitter': (s) => s.brSizeJitter,
    'brAngleJitter': (s) => s.brAngleJitter,
    'brRoundnessJitter': (s) => s.brRoundnessJitter,
    'brOpacityJitter': (s) => s.brOpacityJitter,
    'brSpacingJitter': (s) => s.brSpacingJitter,
    'brMixing': (s) => s.brMixing,
    'brPaintAmount': (s) => s.brPaintAmount,
    'brPaintDensity': (s) => s.brPaintDensity,
    'brColorStretch': (s) => s.brColorStretch,
    'trFlipHorizontal': (s) => s.trFlipHorizontal,
    'trFlipVertical': (s) => s.trFlipVertical,
    'trAnchor': (s) => s.trAnchor,
    'trAnchorOpposite': (s) => s.trAnchorOpposite,
    'trAnchorCenter': (s) => s.trAnchorCenter,
    'trMeshColumns': (s) => s.trMeshColumns,
    'trMeshRows': (s) => s.trMeshRows,
    'brEditGroup': (s) => s.brEditGroup,
    'brFolderName': (s) => s.brFolderName,
    'brFolderIcon': (s) => s.brFolderIcon,
    'commonReset': (s) => s.commonReset,
    'commonFill': (s) => s.commonFill,
    'viewFitToView': (s) => s.viewFitToView,
    'viewResetView': (s) => s.viewResetView,
    'panelSettings': (s) => s.panelSettings,
    'viewRotateLeft': (s) => s.viewRotateLeft,
    'viewRotateRight': (s) => s.viewRotateRight,
    'viewFlipHorizontal': (s) => s.viewFlipHorizontal,
    'viewFlipVertical': (s) => s.viewFlipVertical,
    'viewStraighten': (s) => s.viewStraighten,
    'viewZoomDrag': (s) => s.viewZoomDrag,
    'viewAngleDrag': (s) => s.viewAngleDrag,
    'viewDragDoubleTap': (s) => s.viewDragDoubleTap,
    'viewCanvasColor': (s) => s.viewCanvasColor,
    'viewPasteboardColor': (s) => s.viewPasteboardColor,
    'viewBackdropColor': (s) => s.viewBackdropColor,
    'colorUseCurrent': (s) => s.colorUseCurrent,
    'colorNone': (s) => s.colorNone,
    'tlSections': (s) => s.tlSections,
    'tlAllDisplayedLayers': (s) => s.tlAllDisplayedLayers,
    'tlShowAll': (s) => s.tlShowAll,
    'tlHideAll': (s) => s.tlHideAll,
    'tlSoloKind': (s) => s.tlSoloKind,
    'tlSoloColor': (s) => s.tlSoloColor,
    'tlSoloFillReferences': (s) => s.tlSoloFillReferences,
    'tlSoloFxOnRows': (s) => s.tlSoloFxOnRows,
    'tlSoloSheetOnRows': (s) => s.tlSoloSheetOnRows,
    'tlApplyAllFx': (s) => s.tlApplyAllFx,
    'tlBypassAllFx': (s) => s.tlBypassAllFx,
    'tlAllOnTimesheet': (s) => s.tlAllOnTimesheet,
    'tlAllOffTimesheet': (s) => s.tlAllOffTimesheet,
    'tlClearAllMarks': (s) => s.tlClearAllMarks,
    'tlClearAllFillRefs': (s) => s.tlClearAllFillRefs,
    'tlColVisibility': (s) => s.tlColVisibility,
    'tlColLayerKind': (s) => s.tlColLayerKind,
    'tlColOnionSkin': (s) => s.tlColOnionSkin,
    'tlColOpacity': (s) => s.tlColOpacity,
    'tlColBlendMode': (s) => s.tlColBlendMode,
    'tlColFx': (s) => s.tlColFx,
    'tlColMark': (s) => s.tlColMark,
    'tlColFillReference': (s) => s.tlColFillReference,
    'tlColTimesheet': (s) => s.tlColTimesheet,
    'tlOpenOnionPanel': (s) => s.tlOpenOnionPanel,
    'tlLayerMark': (s) => s.tlLayerMark,
    'tlLayerMarkNone': (s) => s.tlLayerMarkNone,
    'tlLayerMarkSource': (s) => s.tlLayerMarkSource,
    'tlLayerTake': (s) => s.tlLayerTake,
    'tlRepeat': (s) => s.tlRepeat,
    'tlRepeatSelection': (s) => s.tlRepeatSelection,
    'tlSeNameTemplate': (s) => s.tlSeNameTemplate,
    'tlAddLayerHeader': (s) => s.tlAddLayerHeader,
    'tlNoLayers': (s) => s.tlNoLayers,
    'tlLegendLayer': (s) => s.tlLegendLayer,
    'tlAllDisplayedOpacity': (s) => s.tlAllDisplayedOpacity,
    'tlLinkedLayerTooltip': (s) => s.tlLinkedLayerTooltip,
    'tlAudioLane': (s) => s.tlAudioLane,
    'tlNameTagGroup': (s) => s.tlNameTagGroup,
    'tlTransformGroup': (s) => s.tlTransformGroup,
    'tlLaneAnchorPoint': (s) => s.tlLaneAnchorPoint,
    'tlLanePosition': (s) => s.tlLanePosition,
    'tlLaneScale': (s) => s.tlLaneScale,
    'tlLaneRotation': (s) => s.tlLaneRotation,
    'tlLaneOpacity': (s) => s.tlLaneOpacity,
    'tlBypassLaneTemplate': (s) => s.tlBypassLaneTemplate,
    'tlApplyLaneTemplate': (s) => s.tlApplyLaneTemplate,
    'tlRunEdgeNone': (s) => s.tlRunEdgeNone,
    'tlRunEdgeHold': (s) => s.tlRunEdgeHold,
    'tlSelectedFrameRange': (s) => s.tlSelectedFrameRange,
    'tlSelectedLaneRange': (s) => s.tlSelectedLaneRange,
    'tlSelectedCell': (s) => s.tlSelectedCell,
    'tlSelectedPanelRange': (s) => s.tlSelectedPanelRange,
    'semLayer': (s) => s.semLayer,
    'semSelectedLayer': (s) => s.semSelectedLayer,
    'semTrack': (s) => s.semTrack,
    'semSelectedTrack': (s) => s.semSelectedTrack,
    'sbVideoTrack': (s) => s.sbVideoTrack,
    'noticeFillRegionOpen': (s) => s.noticeFillRegionOpen,
    'noticeCameraKeysCopied': (s) => s.noticeCameraKeysCopied,
    'tlSameAsSelected': (s) => s.tlSameAsSelected,
    'tlKindAnimation': (s) => s.tlKindAnimation,
    'tlKindStoryboard': (s) => s.tlKindStoryboard,
    'tlKindImage': (s) => s.tlKindImage,
    'tlKindText': (s) => s.tlKindText,
    'tlKindAdjustment': (s) => s.tlKindAdjustment,
    'tlKindFolder': (s) => s.tlKindFolder,
    'textCelNewTitle': (s) => s.textCelNewTitle,
    'textCelEditTitle': (s) => s.textCelEditTitle,
    'textCelTextLabel': (s) => s.textCelTextLabel,
    'textCelFontLabel': (s) => s.textCelFontLabel,
    'textCelFontSystem': (s) => s.textCelFontSystem,
    'textCelSizeLabel': (s) => s.textCelSizeLabel,
    'textCelAlignLabel': (s) => s.textCelAlignLabel,
    'textCelAlignLeft': (s) => s.textCelAlignLeft,
    'textCelAlignCenter': (s) => s.textCelAlignCenter,
    'textCelAlignRight': (s) => s.textCelAlignRight,
    'textCelColorLabel': (s) => s.textCelColorLabel,
    'textCelBoldLabel': (s) => s.textCelBoldLabel,
    'textCelOutlineLabel': (s) => s.textCelOutlineLabel,
    'textCelBackgroundLabel': (s) => s.textCelBackgroundLabel,
    'textCelPositionLabel': (s) => s.textCelPositionLabel,
    'tlKindSe': (s) => s.tlKindSe,
    'tlKindTransition': (s) => s.tlKindTransition,
    'tlKindCamera': (s) => s.tlKindCamera,
    'tlKindSemanticTemplate': (s) => s.tlKindSemanticTemplate,
    'tlKindInstruction': (s) => s.tlKindInstruction,
    'tlNoriShiro': (s) => s.tlNoriShiro,
    'tlAttachFreeAbove': (s) => s.tlAttachFreeAbove,
    'tlAttachFreeBelow': (s) => s.tlAttachFreeBelow,
    'tlAttachSyncedAbove': (s) => s.tlAttachSyncedAbove,
    'tlAttachSyncedBelow': (s) => s.tlAttachSyncedBelow,
    'tlLayerCommands': (s) => s.tlLayerCommands,
    'tlFrameCommands': (s) => s.tlFrameCommands,
    'tlCut': (s) => s.tlCut,
    'tlLayer': (s) => s.tlLayer,
    'tlFrame': (s) => s.tlFrame,
    'tlDuplicateLayer': (s) => s.tlDuplicateLayer,
    'tlLinkDuplicateLayer': (s) => s.tlLinkDuplicateLayer,
    'tlUnlinkLayer': (s) => s.tlUnlinkLayer,
    'tlRenameLayer': (s) => s.tlRenameLayer,
    'tlCopyLayer': (s) => s.tlCopyLayer,
    'tlDeleteLayer': (s) => s.tlDeleteLayer,
    'tlEffects': (s) => s.tlEffects,
    'tlAddEffectTemplate': (s) => s.tlAddEffectTemplate,
    'tlDropIntoFolderTemplate': (s) => s.tlDropIntoFolderTemplate,
    'tlDropOutOfFolder': (s) => s.tlDropOutOfFolder,
    'tlDropAttachSyncedTemplate': (s) => s.tlDropAttachSyncedTemplate,
    'tlDropAttachFreeTemplate': (s) => s.tlDropAttachFreeTemplate,
    'tlDropDetachAttach': (s) => s.tlDropDetachAttach,
    'tlDetachLayer': (s) => s.tlDetachLayer,
    'tlAttachDropsFxTitle': (s) => s.tlAttachDropsFxTitle,
    'tlAttachDropsFxBody': (s) => s.tlAttachDropsFxBody,
    'tlSelectRowSpan': (s) => s.tlSelectRowSpan,
    'tlSharedEdit': (s) => s.tlSharedEdit,
    'tlAdd': (s) => s.tlAdd,
    'tlBlankX': (s) => s.tlBlankX,
    'tlMark': (s) => s.tlMark,
    'tlAutoFrame': (s) => s.tlAutoFrame,
    'tlSetCommasN': (s) => s.tlSetCommasN,
    'tlSetCommaTemplate': (s) => s.tlSetCommaTemplate,
    'tlProjectAudioRate': (s) => s.tlProjectAudioRate,
    'tlCustom': (s) => s.tlCustom,
    'tlShowSeRows': (s) => s.tlShowSeRows,
    'tlShowCameraRows': (s) => s.tlShowCameraRows,
    'tlStoryboardLayer': (s) => s.tlStoryboardLayer,
    'tlPush': (s) => s.tlPush,
    'tlPull': (s) => s.tlPull,
    'sbOneStoryboardRowPerCut': (s) => s.sbOneStoryboardRowPerCut,
    'cnConte': (s) => s.cnConte,
    'cnActionColumn': (s) => s.cnActionColumn,
    'setCommasTitle': (s) => s.setCommasTitle,
    'setCommasField': (s) => s.setCommasField,
    'projectFpsTitle': (s) => s.projectFpsTitle,
    'projectFpsField': (s) => s.projectFpsField,
  };

  for (final language in AppLanguage.values) {
    test('every string resolves in ${language.name}', () {
      final strings = AppStrings.of(language);
      for (final entry in readers.entries) {
        expect(
          entry.value(strings),
          isNotEmpty,
          reason: '${entry.key} is empty or unresolved in ${language.name}',
        );
      }
    });
  }

  // The shortcut registry resolves by ID, not by getter, so it is checked
  // against the registry itself rather than a hand-listed table — a new
  // action cannot be added without this noticing.
  for (final language in AppLanguage.values) {
    test('every shortcut action and category resolves in ${language.name}', () {
      final strings = AppStrings.of(language);
      for (final definition in editorActionDefinitions) {
        expect(
          strings.shortcutLabel(definition.id, definition.label),
          isNotEmpty,
          reason: '${definition.id} in ${language.name}',
        );
        expect(
          strings.shortcutCategory(definition.category, definition.category),
          isNotEmpty,
          reason: '${definition.category} in ${language.name}',
        );
      }
    });
  }

  test('the reader table covers every getter the class declares', () {
    // Guards the guard: a string added without a line above would otherwise
    // be silently unchecked in the four non-English maps.
    //
    // This used to be `expect(readers, hasLength(<n>))` — a hand-kept number,
    // which meant it could only fail when THIS file changed, never when
    // app_strings.dart gained a getter, which is the one case it exists for.
    // It had drifted 47 getters behind. So it reads the declarations out of
    // the source instead, the way the shortcut half of this file reads the
    // registry: adding a getter and forgetting its line here is now what
    // fails, rather than arithmetic.
    final source = File('lib/src/ui/text/app_strings.dart').readAsStringSync();
    final declared = RegExp(
      '^  String get ([A-Za-z0-9_]+)',
      multiLine: true,
    ).allMatches(source).map((match) => match.group(1)!).toSet();
    // If the scan ever returns nothing the assertions below pass vacuously,
    // which would be the same silent hole in a new disguise.
    expect(declared, hasLength(greaterThan(400)), reason: 'source scan failed');
    expect(
      declared.difference(readers.keys.toSet()),
      isEmpty,
      reason: 'declared in AppStrings but never read here',
    );
    expect(
      readers.keys.toSet().difference(declared),
      isEmpty,
      reason: 'read here but no longer declared in AppStrings',
    );
  });

  test('B9: bar-button writing carries no trailing ellipsis — 編集, not '
      '編集… (유저 2026-08-17: 「심플하게 編集」)', () {
    // The '…' convention belongs to menu ENTRIES that open a dialog; on a
    // bar button it reads as an ellipsized label. These two are the bar
    // buttons that wore it.
    for (final language in AppLanguage.values) {
      final strings = AppStrings.of(language);
      for (final entry in {
        'tlSharedEdit': strings.tlSharedEdit,
        'tlSetCommasN': strings.tlSetCommasN,
      }.entries) {
        expect(
          entry.value.endsWith('…') || entry.value.endsWith('...'),
          isFalse,
          reason: '${entry.key} in ${language.name} ends with an ellipsis',
        );
      }
    }
    // The reported case, verbatim: the edit button says 編集 and nothing
    // more.
    expect(AppStrings.of(AppLanguage.ja).tlSharedEdit, '編集');
  });
}
